# Generated by Django 4.2.7 on 2024-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(max_length=100, unique=True)),
                ('cari_ad', models.CharField(blank=True, max_length=255, null=True)),
                ('satici', models.CharField(blank=True, max_length=255, null=True)),
                ('grup', models.CharField(max_length=50)),
                ('odemekosulu', models.CharField(blank=True, max_length=255, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('monthly_balances', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(max_length=100)),
                ('cari_ad', models.CharField(max_length=255)),
                ('satici', models.CharField(blank=True, max_length=255, null=True)),
                ('grup', models.CharField(max_length=50)),
                ('belge_tarih', models.CharField(blank=True, max_length=10, null=True)),
                ('vade_tarih', models.CharField(blank=True, max_length=10, null=True)),
                ('belge_no', models.IntegerField()),
                ('odemekod', models.IntegerField()),
                ('odemekosulu', models.CharField(max_length=255)),
                ('borc', models.DecimalField(decimal_places=2, max_digits=19)),
                ('alacak', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'ordering': ['belge_tarih'],
            },
        ),
    ]
