# Generated by Django 4.2.7 on 2024-04-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customercollection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierPayment',
            new_name='CustomerCollection',
        ),
    ]
