# Generated by Django 4.2.7 on 2024-04-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customercollection', '0002_rename_supplierpayment_customercollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closinginvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='closinginvoice',
            name='updated_at',
        ),
    ]
