# Generated by Django 4.2.7 on 2024-06-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercollection', '0003_remove_closinginvoice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='grup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
