# Generated by Django 5.0.8 on 2025-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TunaInsSupplierAdvanceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muhatap_kod', models.CharField(max_length=50, unique=True, verbose_name='Muhatap Kod')),
                ('muhatap_ad', models.CharField(max_length=255, verbose_name='Muhatap Adı')),
                ('avans_bakiye', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Avans Bakiye')),
            ],
            options={
                'verbose_name': 'Tedarikci Avans Raporu',
                'verbose_name_plural': 'Tedarikci Avans Raporlari',
            },
        ),
    ]
