# Generated by Django 5.0.8 on 2025-07-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Yüklenen dosyanın orijinal adı', max_length=255)),
                ('file_path', models.TextField(help_text='Sunucuda saklanan dosyanın tam yolu')),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Belgedeki toplam sayfa sayısı')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Yükleme zamanı')),
                ('parsed_at', models.DateTimeField(blank=True, help_text='PDF analizinin tamamlandığı zaman', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('error', 'Error')], default='pending', help_text='İşlenme durumu', max_length=50)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_id', models.CharField(help_text='DOC001-PAGE003-CHUNK007 gibi benzersiz ID', max_length=64, unique=True)),
                ('page_number', models.PositiveIntegerField(help_text="Bu chunk'ın bulunduğu sayfa")),
                ('section_title', models.CharField(blank=True, help_text='Chunk başlığı (varsa)', max_length=255, null=True)),
                ('content', models.TextField(help_text='Chunk içinde yer alan metin içeriği')),
                ('left_x', models.FloatField()),
                ('bottom_y', models.FloatField()),
                ('right_x', models.FloatField()),
                ('top_y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='heliosforgev2.document')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'ordering': ['document', 'page_number', 'chunk_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Görsel dosya adı (örneğin: DOC001-PAGE002-IMG001.png)', max_length=255)),
                ('file_path', models.TextField(help_text='Görselin sunucudaki tam dosya yolu')),
                ('page_number', models.PositiveIntegerField(help_text='Görselin yer aldığı sayfa numarası')),
                ('left_x', models.FloatField(blank=True, null=True)),
                ('bottom_y', models.FloatField(blank=True, null=True)),
                ('right_x', models.FloatField(blank=True, null=True)),
                ('top_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='heliosforgev2.chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='heliosforgev2.document')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['document', 'page_number', 'file_name'],
            },
        ),
    ]
