# Generated by Django 5.0.8 on 2025-07-07 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heliosforgev2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=datetime.datetime(2025, 7, 7, 8, 38, 29, 205643, tzinfo=datetime.timezone.utc), help_text='Yüklenen PDF dosyası', upload_to='pdf/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='PDF içindeki toplam sayfa'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
