# Generated by Django 5.0.8 on 2025-07-08 08:00

import heliosforgev2.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heliosforgev2', '0002_remove_document_file_name_remove_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Yüklenen PDF dosyası', upload_to=heliosforgev2.models.document.get_pdf_upload_path),
        ),
    ]
