# Generated by Django 4.2.7 on 2024-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdrDetailOpqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniq_detail_no', models.CharField(max_length=255, unique=True)),
                ('belge_no', models.CharField(db_index=True, max_length=255)),
                ('satici', models.CharField(db_index=True, max_length=255)),
                ('belge_tarih', models.DateField(db_index=True)),
                ('teslim_tarih', models.DateField(db_index=True)),
                ('belge_onay', models.CharField(max_length=10)),
                ('belge_status', models.CharField(db_index=True, max_length=10)),
                ('sevk_adres', models.CharField(blank=True, max_length=255, null=True)),
                ('musteri_kod', models.CharField(db_index=True, max_length=255)),
                ('musteri_ad', models.CharField(max_length=255)),
                ('satis_tipi', models.CharField(max_length=255)),
                ('kalem_grup_kod', models.IntegerField(db_index=True)),
                ('kalem_grup', models.CharField(max_length=255)),
                ('satir_status', models.CharField(db_index=True, max_length=10)),
                ('kalem_kod', models.CharField(db_index=True, max_length=255)),
                ('kalem_tanimi', models.CharField(max_length=255)),
                ('birim', models.CharField(max_length=50)),
                ('sip_miktar', models.FloatField()),
                ('sevk_miktar', models.FloatField()),
                ('kalan_miktar', models.FloatField()),
                ('liste_fiyat_dpb', models.FloatField()),
                ('detay_kur', models.FloatField()),
                ('detay_doviz', models.CharField(max_length=10)),
                ('iskonto_oran', models.FloatField()),
                ('net_fiyat_dpb', models.FloatField()),
                ('net_tutar_ypb', models.FloatField()),
                ('acik_net_tutar_ypb', models.FloatField()),
                ('girsberger_net_tutar_ypb', models.FloatField()),
                ('salma_teklif_tedarikci_kod', models.CharField(blank=True, max_length=255, null=True)),
                ('salma_teklif_tedarikci_ad', models.CharField(blank=True, max_length=255, null=True)),
                ('salma_teklif_no', models.CharField(blank=True, max_length=255, null=True)),
                ('salma_teklif_kaynak_detay_no', models.CharField(blank=True, max_length=255, null=True)),
                ('salma_teklif_kalem_no', models.CharField(blank=True, max_length=255, null=True)),
                ('salma_teklif_miktar', models.FloatField(blank=True, null=True)),
                ('salma_teklif_sevk', models.FloatField(blank=True, null=True)),
                ('salma_teklif_kalan_miktar', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['uniq_detail_no'], name='girsbergero_uniq_de_08329d_idx'), models.Index(fields=['belge_no'], name='girsbergero_belge_n_de06bb_idx'), models.Index(fields=['satici'], name='girsbergero_satici_ca2c1d_idx'), models.Index(fields=['belge_tarih'], name='girsbergero_belge_t_d0ff61_idx'), models.Index(fields=['teslim_tarih'], name='girsbergero_teslim__036d58_idx'), models.Index(fields=['belge_status'], name='girsbergero_belge_s_006024_idx'), models.Index(fields=['musteri_kod'], name='girsbergero_musteri_19fe5f_idx'), models.Index(fields=['kalem_grup_kod'], name='girsbergero_kalem_g_22b30a_idx'), models.Index(fields=['satir_status'], name='girsbergero_satir_s_a787cd_idx'), models.Index(fields=['kalem_kod'], name='girsbergero_kalem_k_fb2d8c_idx')],
            },
        ),
    ]
