# Generated by Django 4.2.7 on 2024-05-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girsbergerordropqt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordrdetailopqt',
            name='girsbergero_belge_s_006024_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordrdetailopqt',
            name='girsbergero_kalem_g_22b30a_idx',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='acik_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='belge_onay',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='belge_status',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='birim',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='detay_doviz',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='detay_kur',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='girsberger_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='iskonto_oran',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='kalan_miktar',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='kalem_grup',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='kalem_grup_kod',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='liste_fiyat_dpb',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='net_fiyat_dpb',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='salma_teklif_kalan_miktar',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='salma_teklif_sevk',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='sevk_adres',
        ),
        migrations.RemoveField(
            model_name='ordrdetailopqt',
            name='sevk_miktar',
        ),
    ]
