# Generated by Django 5.0.8 on 2025-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satıcı')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sipariş No')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Sipariş Tarihi')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri Kod')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Müşteri Adı')),
                ('document_description', models.TextField(blank=True, null=True, verbose_name='Belge Açıklama')),
                ('color_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='Renk Kod')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='Detay Açıklama')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='Sıra No')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalem Kod')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='Kalem Tanım')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Birim Fiyat')),
                ('vat_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='KDV Yüzde')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='KDV Tutar')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='İskonto Oran')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='İskontolu Tutar')),
                ('currency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Döviz')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True, verbose_name='Kur')),
                ('currency_price', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Döviz Fiyat')),
                ('currency_movement_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Döviz Hareket Tutar')),
            ],
        ),
    ]
