// frontend/src/redux/actions/salesbudgetv2/actionTypesv2.js
// Yerel bütçe verileri eylem tipleri
export const FETCH_LOCAL_SALES_BUDGET_REQUEST = 'FETCH_LOCAL_SALES_BUDGET_REQUEST_V2';
export const FETCH_LOCAL_SALES_BUDGET_SUCCESS = 'FETCH_LOCAL_SALES_BUDGET_SUCCESS_V2';
export const FETCH_LOCAL_SALES_BUDGET_FAILURE = 'FETCH_LOCAL_SALES_BUDGET_FAILURE_V2';

// HANA bütçe verileri eylem tipleri
export const FETCH_HANA_SALES_BUDGET_REQUEST = 'FETCH_HANA_SALES_BUDGET_REQUEST_V2';
export const FETCH_HANA_SALES_BUDGET_SUCCESS = 'FETCH_HANA_SALES_BUDGET_SUCCESS_V2';
export const FETCH_HANA_SALES_BUDGET_FAILURE = 'FETCH_HANA_SALES_BUDGET_FAILURE_V2';


