# Generated by Django 4.2.7 on 2024-03-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersalesorder',
            name='grup',
            field=models.CharField(default=6, max_length=25, verbose_name='Grup'),
            preserve_default=False,
        ),
    ]
