# Generated by Django 5.0.8 on 2025-08-22 13:18

import django.db.models.deletion
import nexuscore.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu bağlantıyı tanımlayan benzersiz bir başlık (örn: Üretim SQL Sunucusu).', max_length=255, unique=True)),
                ('db_type', models.CharField(choices=[('POSTGRESQL', 'PostgreSQL'), ('SQL_SERVER', 'Microsoft SQL Server'), ('MYSQL', 'MySQL'), ('ORACLE', 'Oracle'), ('HANA', 'SAP HANA'), ('OTHER', 'Diğer')], default='OTHER', help_text='Veri tabanı türü (örn: PostgreSQL, SQL Server).', max_length=20)),
                ('json_config', nexuscore.models.fields.EncryptedJSONField(help_text='Django DATABASES ayarlarıyla uyumlu, şifrelenmiş JSON yapılandırması.')),
                ('is_active', models.BooleanField(default=False, help_text='Sistem genelinde sorgular için varsayılan olarak kullanılacak mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dinamik Veri Tabanı Bağlantısı',
                'verbose_name_plural': 'Dinamik Veri Tabanı Bağlantıları',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='...', max_length=255)),
                ('sql_query', models.TextField(help_text='...')),
                ('column_metadata', models.JSONField(blank=True, default=dict, help_text='...')),
                ('sharing_status', models.CharField(choices=[('PRIVATE', 'Özel (Sadece Sahibi Görebilir)'), ('PUBLIC_READONLY', 'Halka Açık (Sadece Görüntülenebilir)'), ('PUBLIC_EDITABLE', 'Halka Açık (Herkes Düzenleyebilir)')], default='PRIVATE', help_text='Bu sanal tablonun diğer kullanıcılar için görünürlük ve düzenleme ayarı.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tables', to='nexuscore.dynamicdbconnection')),
                ('owner', models.ForeignKey(help_text='...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanal Tablo',
                'verbose_name_plural': 'Sanal Tablolar',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'connection', 'title')},
            },
        ),
    ]
