# Generated by Django 5.0.8 on 2025-08-26 09:07

import django.db.models.deletion
import nexuscore.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Bağlantı Başlığı')),
                ('db_type', models.CharField(help_text='Örn: postgresql, sql_server, sap_hana', max_length=50, verbose_name='Veritabanı Türü')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu bağlantının sorgularda kullanılıp kullanılamayacağını belirtir.', verbose_name='Aktif mi?')),
                ('config_json', nexuscore.fields.EncryptedJSONField(default=dict, help_text='Hassas bağlantı bilgileri (şifre, host vb.) bu alanda şifrelenerek saklanır.', verbose_name='Bağlantı Yapılandırması (Şifreli JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_connections', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Dinamik Veritabanı Bağlantısı',
                'verbose_name_plural': 'Dinamik Veritabanı Bağlantıları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='...', max_length=255)),
                ('sql_query', models.TextField(help_text='...')),
                ('column_metadata', models.JSONField(blank=True, default=dict, help_text='...')),
                ('sharing_status', models.CharField(choices=[('PRIVATE', 'Özel (Sadece Sahibi Görebilir)'), ('PUBLIC_READONLY', 'Halka Açık (Sadece Görüntülenebilir)'), ('PUBLIC_EDITABLE', 'Halka Açık (Herkes Düzenleyebilir)')], default='PRIVATE', help_text='Bu sanal tablonun diğer kullanıcılar için görünürlük ve düzenleme ayarı.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tables', to='nexuscore.dynamicdbconnection')),
                ('owner', models.ForeignKey(help_text='...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanal Tablo',
                'verbose_name_plural': 'Sanal Tablolar',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'connection', 'title')},
            },
        ),
    ]
