# Generated by Django 5.2.5 on 2025-08-27 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuscore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Rapor Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('configuration_json', models.JSONField(blank=True, default=dict, help_text='Kolon sırası, görünürlüğü, filtreler vb. ayarları içerir.', verbose_name='Rapor Yapılandırması (JSON)')),
                ('sharing_status', models.CharField(choices=[('PRIVATE', 'Özel (Sadece Sahibi Görebilir)'), ('PUBLIC_READONLY', 'Halka Açık (Sadece Görüntülenebilir)'), ('PUBLIC_EDITABLE', 'Halka Açık (Herkes Düzenleyebilir)')], default='PRIVATE', max_length=20, verbose_name='Paylaşım Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
                ('source_virtual_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='nexuscore.virtualtable', verbose_name='Kaynak Sanal Tablo')),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
                'ordering': ['-updated_at'],
            },
        ),
    ]
