# Generated by Django 5.2.5 on 2025-08-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuscore', '0002_reporttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtable',
            name='column_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Sütunların görünürlüğü gibi UI ayarlarını saklar.', verbose_name='Sütun Meta Verisi'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='connection',
            field=models.ForeignKey(help_text='Bu sanal tablonun sorguyu çalıştıracağı veri kaynağı.', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tables', to='nexuscore.dynamicdbconnection', verbose_name='Veri Kaynağı Bağlantısı'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='owner',
            field=models.ForeignKey(help_text='Bu sanal tabloyu oluşturan veya sahibi olan kullanıcı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_tables', to=settings.AUTH_USER_MODEL, verbose_name='Sahip'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='sharing_status',
            field=models.CharField(choices=[('PRIVATE', 'Özel (Sadece Sahibi Görebilir)'), ('PUBLIC_READONLY', 'Halka Açık (Sadece Görüntülenebilir)'), ('PUBLIC_EDITABLE', 'Halka Açık (Herkes Düzenleyebilir)')], default='PRIVATE', help_text='Bu sanal tablonun diğer kullanıcılar için görünürlük ayarı.', max_length=20, verbose_name='Paylaşım Durumu'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='sql_query',
            field=models.TextField(help_text='Çalıştırılacak olan SELECT veya WITH ile başlayan SQL sorgusu.', verbose_name='SQL Sorgusu'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='title',
            field=models.CharField(help_text='Sanal tabloya verilen, kolay hatırlanabilir isim.', max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='virtualtable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
