# Generated by Django 5.2.5 on 2025-09-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuscore', '0003_alter_virtualtable_column_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='source_virtual_table',
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='configuration_json',
            field=models.JSONField(blank=True, default=dict, help_text='Pivot ayarları, filtreler vb. ayarları içerir.', verbose_name='Rapor Yapılandırması (JSON)'),
        ),
        migrations.CreateModel(
            name='DataApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Uygulama Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('sharing_status', models.CharField(choices=[('PRIVATE', 'Özel (Sadece Sahibi Görebilir)'), ('PUBLIC_READONLY', 'Halka Açık (Sadece Görüntülenebilir)'), ('PUBLIC_EDITABLE', 'Halka Açık (Herkes Düzenleyebilir)')], default='PRIVATE', max_length=20, verbose_name='Paylaşım Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_apps', to='nexuscore.dynamicdbconnection', verbose_name='Veri Kaynağı')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_apps', to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
                ('virtual_tables', models.ManyToManyField(help_text='Bu uygulamada kullanılacak veri kümeleri.', related_name='data_apps', to='nexuscore.virtualtable', verbose_name='İçerilen Sanal Tablolar')),
            ],
            options={
                'verbose_name': 'Veri Uygulaması',
                'verbose_name_plural': 'Veri Uygulamaları',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AppRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_column', models.CharField(help_text='JOIN için kullanılacak kolon adı (Örn: MusteriID)', max_length=255, verbose_name='Sol Tablo Kolonu')),
                ('right_column', models.CharField(help_text='JOIN için kullanılacak kolon adı (Örn: ID)', max_length=255, verbose_name='Sağ Tablo Kolonu')),
                ('join_type', models.CharField(choices=[('INNER JOIN', 'İç Birleştirme (INNER JOIN)'), ('LEFT JOIN', 'Sol Birleştirme (LEFT JOIN)')], default='LEFT JOIN', max_length=20, verbose_name='Birleştirme Türü')),
                ('left_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_relations', to='nexuscore.virtualtable', verbose_name='Sol Tablo')),
                ('right_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_relations', to='nexuscore.virtualtable', verbose_name='Sağ Tablo')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='nexuscore.dataapp', verbose_name='Ait Olduğu Uygulama')),
            ],
            options={
                'verbose_name': 'Uygulama İlişkisi',
                'verbose_name_plural': 'Uygulama İlişkileri',
                'ordering': ['app'],
            },
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='source_data_app',
            field=models.ForeignKey(blank=True, help_text='Bu raporun veri çektiği ana veri modeli.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='nexuscore.dataapp', verbose_name='Kaynak Veri Uygulaması'),
        ),
    ]
