# Generated by Django 5.2.5 on 2025-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuscore', '0004_remove_reporttemplate_source_virtual_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(help_text="Veritabanı türü (örn: 'sap_hana', 'sql_server')", max_length=50)),
                ('source_type', models.CharField(help_text='Veritabanından gelen orijinal tip kodu/adı', max_length=255, unique=True)),
                ('general_category', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('other', 'Other')], default='other', help_text='Eşleşen genel kategori', max_length=20)),
            ],
            options={
                'verbose_name': 'Veri Tipi Eşleştirme',
                'verbose_name_plural': 'Veri Tipi Eşleştirmeleri',
                'ordering': ['db_type', 'source_type'],
                'unique_together': {('db_type', 'source_type')},
            },
        ),
    ]
