# Generated by Django 5.2.5 on 2025-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuscore', '0005_dbtypemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtypemapping',
            name='general_category',
            field=models.CharField(choices=[('string', 'Metin (String)'), ('integer', 'Tamsayı (Integer)'), ('decimal', 'Ondalıklı Sayı (Decimal)'), ('date', 'Tarih (Date)'), ('datetime', 'Tarih ve Zaman (DateTime)'), ('boolean', 'Mantıksal (Boolean)'), ('json', 'JSON'), ('other', 'Diğer/Bilinmeyen')], default='other', help_text='Eşleşen genel kategori', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbtypemapping',
            name='source_type',
            field=models.CharField(help_text="Veritabanından gelen orijinal tip kodu/adı (örn: 'NVARCHAR', '1043')", max_length=255),
        ),
    ]
