# Generated by Django 4.2.7 on 2024-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(max_length=20, unique=True)),
                ('cari_adi', models.CharField(blank=True, max_length=255, null=True)),
                ('temsilci', models.CharField(blank=True, max_length=255, null=True)),
                ('cari_grup', models.CharField(blank=True, max_length=255, null=True)),
                ('bugun', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bugun_minus_1', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bugun_minus_2', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bugun_minus_3', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bugun_minus_4', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bu_ay_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bu_ay_minus_1_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bugun_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bugun_minus_1_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bugun_minus_2_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bugun_minus_3_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bugun_minus_4_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bu_ay_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('bu_ay_minus_1_ilgili_siparis_numaralari', models.CharField(default='0', max_length=500)),
                ('acik_irsaliye_belge_no_tarih_tutar', models.CharField(default='0', max_length=1000)),
                ('yillik_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('acik_sevkiyat_toplami', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('acik_siparis_toplami', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('irsaliye_sayisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Delivery Document Summary',
                'verbose_name_plural': 'Delivery Document Summaries',
            },
        ),
    ]
