# Generated by Django 4.2.7 on 2024-06-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverydocsumv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='acik_irsaliye_belge_no_tarih_tutar',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bu_ay_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bu_ay_minus_1_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bugun_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bugun_minus_1_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bugun_minus_2_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bugun_minus_3_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='bugun_minus_4_ilgili_siparis_numaralari',
            field=models.TextField(default='0'),
        ),
    ]
