# Generated by Django 4.2.7 on 2024-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('satici', models.CharField(max_length=255)),
                ('belge_tur', models.CharField(max_length=50)),
                ('onay1_status', models.CharField(max_length=10)),
                ('onay2_status', models.CharField(max_length=10)),
                ('belge_tarihi', models.DateField()),
                ('teslim_tarihi', models.DateField()),
                ('belge_onay', models.CharField(max_length=10)),
                ('belge_status', models.CharField(max_length=10)),
                ('musteri_kod', models.CharField(max_length=50)),
                ('musteri_ad', models.CharField(max_length=255)),
                ('belge_giris_no', models.IntegerField()),
                ('sip_no', models.CharField(max_length=50)),
                ('satis_tipi', models.CharField(max_length=50)),
                ('kalem_grup', models.CharField(max_length=50)),
                ('satir_status', models.CharField(max_length=10)),
                ('satir_no', models.IntegerField()),
                ('depo_kod', models.CharField(max_length=50)),
                ('kalem_kod', models.CharField(max_length=50)),
                ('kalem_tanimi', models.CharField(max_length=255)),
                ('birim', models.CharField(max_length=50)),
                ('sip_miktar', models.DecimalField(decimal_places=4, max_digits=18)),
                ('sevk_miktar', models.DecimalField(decimal_places=4, max_digits=18)),
                ('kalan_miktar', models.DecimalField(decimal_places=4, max_digits=18)),
                ('liste_fiyat_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('detay_kur', models.DecimalField(decimal_places=4, max_digits=18)),
                ('detay_doviz', models.CharField(max_length=3)),
                ('iskonto_oran', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_fiyat_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('brut_tutar_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_tutar_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('isk_tutar_dpb', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kdv_tutar_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('kdvli_net_tutar_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('belge_kur', models.DecimalField(decimal_places=4, max_digits=18)),
                ('belge_doviz', models.CharField(max_length=3)),
                ('liste_fiyat_ypb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('brut_tutar_ypb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('isk_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_tutar_ypb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('kdv_oran', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kdv_grubu', models.CharField(max_length=50)),
                ('kdv_tutar_ypb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('kdvli_net_tutar_ypb', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'verbose_name': 'Satış Sipariş Detayı',
                'verbose_name_plural': 'Satış Sipariş Detayları',
            },
        ),
    ]
