# Generated by Django 4.2.7 on 2024-03-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_doviz',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_giris_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_kur',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_onay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_tarihi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_tur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='birim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='brut_tutar_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='brut_tutar_ypb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='depo_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='detay_doviz',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='detay_kur',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_dpb',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_ypb',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='iskonto_oran',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalan_miktar',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalem_grup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalem_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalem_tanimi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_grubu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_oran',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_tutar_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_tutar_ypb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdvli_net_tutar_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdvli_net_tutar_ypb',
            field=models.DecimalField(decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='liste_fiyat_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='liste_fiyat_ypb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='musteri_ad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='musteri_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_fiyat_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_tutar_dpb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='onay1_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='onay2_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satici',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satir_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satir_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sevk_miktar',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sip_miktar',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sip_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='teslim_tarihi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
