# Generated by Django 4.2.7 on 2024-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0002_alter_salesorderdetail_belge_doviz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='unique_id',
            field=models.CharField(max_length=255),
        ),
    ]
