# Generated by Django 4.2.7 on 2024-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0005_alter_salesorderdetail_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='unique_id',
            field=models.CharField(default=5554, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
