# Generated by Django 4.2.7 on 2024-03-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0006_alter_salesorderdetail_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('satici', models.CharField(blank=True, max_length=255, null=True)),
                ('belge_tur', models.CharField(blank=True, max_length=50, null=True)),
                ('onay1_status', models.CharField(blank=True, max_length=10, null=True)),
                ('onay2_status', models.CharField(blank=True, max_length=10, null=True)),
                ('belge_tarihi', models.CharField(blank=True, max_length=10, null=True)),
                ('teslim_tarihi', models.CharField(blank=True, max_length=10, null=True)),
                ('belge_onay', models.CharField(blank=True, max_length=10, null=True)),
                ('belge_status', models.CharField(blank=True, max_length=10, null=True)),
                ('musteri_kod', models.CharField(blank=True, max_length=50, null=True)),
                ('musteri_ad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Satış Sipariş Ana Bilgisi',
                'verbose_name_plural': 'Satış Sipariş Ana Bilgileri',
            },
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_onay',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_status',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_tarihi',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_tur',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='musteri_ad',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='musteri_kod',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='onay1_status',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='onay2_status',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='satici',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='teslim_tarihi',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_kur',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='brut_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='brut_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='detay_kur',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='iskonto_oran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalan_miktar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_oran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdvli_net_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdvli_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='liste_fiyat_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='liste_fiyat_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_fiyat_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sevk_miktar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sip_miktar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='master',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='salesorderdetail.salesordermaster'),
            preserve_default=False,
        ),
    ]
