# Generated by Django 4.2.7 on 2024-03-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0007_salesordermaster_remove_salesorderdetail_belge_onay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='kdv_grubu',
        ),
    ]
