# Generated by Django 4.2.7 on 2024-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0009_remove_salesorderdetail_belge_doviz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesordermaster',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
