# Generated by Django 4.2.7 on 2024-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0011_remove_salesordermaster_belge_doviz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_doviz',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_giris_no',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='belge_kur',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='satis_tipi',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='sip_no',
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='belge_doviz',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='belge_giris_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='belge_kur',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='sip_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
