# Generated by Django 4.2.7 on 2024-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0012_remove_salesorderdetail_belge_doviz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdetail',
            name='master_unique_id',
            field=models.CharField(default=8, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
