# Generated by Django 4.2.7 on 2024-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0013_salesorderdetail_master_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesordermaster',
            name='belge_giris_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
