# Generated by Django 4.2.7 on 2024-03-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0014_alter_salesordermaster_belge_giris_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordermaster',
            name='belge_giris_no',
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='detay_belge_giris_no',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesordermaster',
            name='master_belge_giris_no',
            field=models.IntegerField(default=16, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
