# Generated by Django 4.2.7 on 2024-03-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0015_remove_salesordermaster_belge_giris_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='detay_belge_giris_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesordermaster',
            name='master_belge_giris_no',
            field=models.IntegerField(unique=True),
        ),
    ]
