# Generated by Django 4.2.7 on 2024-03-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0016_alter_salesorderdetail_detay_belge_giris_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesordermaster',
            name='master_belge_giris_no',
            field=models.IntegerField(),
        ),
    ]
