# Generated by Django 4.2.7 on 2024-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0017_alter_salesordermaster_master_belge_giris_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_dpb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='isk_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='iskonto_oran',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdv_oran',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kdvli_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesordermaster',
            name='belge_doviz',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
