# Generated by Django 4.2.7 on 2024-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0018_alter_salesorderdetail_isk_tutar_dpb_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesorderdetail',
            constraint=models.UniqueConstraint(fields=('master', 'detay_belge_giris_no'), name='unique_master_detay'),
        ),
    ]
