# Generated by Django 4.2.7 on 2024-03-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0019_salesorderdetail_unique_master_detay'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderdetail',
            name='unique_master_detay',
        ),
    ]
