# Generated by Django 4.2.7 on 2024-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0020_remove_salesorderdetail_unique_master_detay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='master_unique_id',
            new_name='detay_unique_id',
        ),
        migrations.RenameField(
            model_name='salesordermaster',
            old_name='unique_id',
            new_name='master_unique_id',
        ),
    ]
