# Generated by Django 4.2.7 on 2024-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdetail', '0021_rename_master_unique_id_salesorderdetail_detay_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='detay_unique_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
