# Generated by Django 4.2.7 on 2024-05-30 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_title', models.CharField(max_length=255, verbose_name='Görev Başlığı')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='Proje Adı')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Son Tarih')),
                ('task_description', models.TextField(blank=True, verbose_name='Görev Açıklamaları')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla'), (2, 'Arşiv')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
