# Generated by Django 5.0.8 on 2025-03-01 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(help_text='Stok Kodu (ItemCode)', max_length=50, unique=True)),
                ('item_name', models.CharField(help_text='Stok Tanımı (ItemName)', max_length=200)),
                ('items_group_code', models.IntegerField(choices=[(105, 'Mamul'), (103, 'Ticari'), (112, 'Girsberger')], help_text='Ürün Grubu Kodu (ItemsGroupCode)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fiyat', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Para Birimi', max_length=10)),
                ('hana_status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', help_text='HANA DB ile Senkronizasyon Durumu', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Son Senkronizasyon Zamanı', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
