# Generated by Django 5.0.8 on 2025-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcardintegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='SAP Payload JSON verisi'),
        ),
    ]
