# Generated by Django 5.0.8 on 2025-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcardintegration', '0003_stockcard_created_by_stockcard_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='item_code',
            field=models.CharField(help_text='Stok Kodu (ItemCode)', max_length=50),
        ),
    ]
