# Generated by Django 5.0.8 on 2025-05-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcardintegration', '0005_fieldhelptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Fiyat', max_digits=19),
        ),
    ]
