# Generated by Django 5.0.8 on 2025-06-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcardintegration', '0006_alter_stockcard_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldhelptext',
            options={'ordering': ['id']},
        ),
    ]
