# Generated by Django 5.0.8 on 2025-08-04 07:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcardintegration', '0007_alter_fieldhelptext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Ürün Kodu')),
                ('item_name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('price_list_name', models.CharField(default='YOK', max_length=120, verbose_name='Satış Fiyat Listesi')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Satış Fiyatı')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('old_component_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Eski Bileşen Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Ürün Fiyat Listesi Kaydı',
                'verbose_name_plural': 'Ürün Fiyat Listeleri',
                'db_table': 'product_price_list',
                'ordering': ['item_code'],
                'indexes': [models.Index(fields=['item_code'], name='idx_ppl_itemcode'), models.Index(fields=['price_list_name'], name='idx_ppl_pricelist')],
            },
        ),
    ]
