# Generated by Django 4.2.7 on 2024-04-19 08:34

from django.db import migrations, models
import docarchive.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=docarchive.models.models.document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
