# Generated by Django 4.2.7 on 2024-04-23 13:30

from django.db import migrations, models
import django.db.models.deletion
import docarchive.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('docarchive', '0002_department_document_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=docarchive.models.models.document_upload_path)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docarchive.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
