# Generated by Django 5.0.8 on 2025-02-12 10:39

import django.db.models.deletion
import newcustomerform.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCustomerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('firma_unvani', models.CharField(max_length=255, verbose_name='Firma Ünvanı')),
                ('vergi_kimlik_numarasi', models.CharField(max_length=50, verbose_name='Vergi Kimlik Numarası / T.C. Kimlik No')),
                ('vergi_dairesi', models.CharField(max_length=255, verbose_name='Vergi Dairesi')),
                ('firma_adresi', models.TextField(verbose_name='Firma Adresi')),
                ('telefon_numarasi', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('muhasebe_irtibat_telefon', models.CharField(max_length=20, verbose_name='Muhasebe İrtibat Telefonu')),
                ('muhasebe_irtibat_email', models.EmailField(max_length=254, verbose_name='Muhasebe İrtibat E-posta')),
                ('odeme_sartlari', models.TextField(verbose_name='Ödeme Şartları ve Vadeleri')),
                ('iskonto_anlasmasi', models.TextField(blank=True, null=True, verbose_name='İskonto veya Özel Fiyat Anlaşması')),
                ('vergi_levhasi', models.FileField(blank=True, null=True, upload_to='new_customer_attachments/', validators=[newcustomerform.models.models.validate_file_size], verbose_name='Vergi Levhası')),
                ('faaliyet_belgesi', models.FileField(blank=True, null=True, upload_to='new_customer_attachments/', validators=[newcustomerform.models.models.validate_file_size], verbose_name='Faaliyet Belgesi')),
                ('ticaret_sicil', models.FileField(blank=True, null=True, upload_to='new_customer_attachments/', validators=[newcustomerform.models.models.validate_file_size], verbose_name='Ticaret Sicil Gazetesi')),
                ('imza_sirkuleri', models.FileField(blank=True, null=True, upload_to='new_customer_attachments/', validators=[newcustomerform.models.models.validate_file_size], verbose_name='İmza Sirküleri')),
                ('banka_iban', models.FileField(blank=True, null=True, upload_to='new_customer_attachments/', validators=[newcustomerform.models.models.validate_file_size], verbose_name='Banka IBAN Bilgileri')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_forms', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yeni Müşteri Formu',
                'verbose_name_plural': 'Yeni Müşteri Formları',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('ad_soyad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkili Kişi Adı Soyadı')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yetkili Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Yetkili E-posta')),
                ('new_customer_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_kisiler', to='newcustomerform.newcustomerform', verbose_name='Yeni Müşteri Formu')),
            ],
            options={
                'verbose_name': 'Yetkili Kişi',
                'verbose_name_plural': 'Yetkili Kişiler',
            },
        ),
    ]
