# backend/productconfigv2/management/commands/setup_follow.py
from django.core.management.base import BaseCommand
from productconfigv2.models import (
    ProductFamily, Product, SpecificationType,
    SpecOption, ProductSpecification, SpecificationOption
)
from collections import defaultdict

# Excel verilerini temsil eden veri seti.
# Her satır: (sıra no, özellik, özellik seçeneği, variant_code, variant_description)
BEEWORK_DATA = [
    (10, "ETAJER VAR MI?", "EVET ETAJERLİ", "-", "ETAJERLİ"),
(10, "ETAJER VAR MI?", "HAYIR ETAJER YOK", "-", "-"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ALPI 10.43 KAPLAMA", "K4", "MASA TABLA ALPI10.43"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ALPI 10.51 KAPLAMA", "K1", "MASA TABLA ALPI10.51"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ALPI 12.12 KAPLAMA", "K2", "MASA TABLA ALPI12.12"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ALPI 12.94 KAPLAMA", "K5", "MASA TABLA ALPI12.94"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ALPI 12.96 KAPLAMA", "K3", "MASA TABLA ALPI12.96"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI AND.CEVIZ LAMINAT", "L7", "MASA TABLA AND.CEVIZ LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI ANTRASIT LAMINAT", "L5", "MASA TABLA ANTRASIT LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI BEJ LAMINAT", "L2", "MASA TABLA BEJ LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI BEYAZ LAMINAT", "L1", "MASA TABLA BEYAZ LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI BRONCE MESE KAPLAMA", "K6", "MASA TABLA BRONCE MESE"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI KAPLAMA", "K0", "MASA TABLASI KAPLAMA"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI KUMBEJI LAMINAT", "L3", "MASA TABLA KUMBEJI LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI LAMINAT", "L0", "MASA TABLA LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI SAFIR MESE LAMINAT", "L8", "MASA TABLA S.MESE LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI VIZON LAMINAT", "L4", "MASA TABLA VIZON LAM"),
(20, "MASA TABLASI MALZEME VE RENK", "MASA TABLASI YENI CEVIZ LAMINAT", "L6", "MASA TABLA Y.CEVIZ LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALPI 10.43 KAPLAMA", "K4", "FLAP ALPI10.43"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALPI 10.51 KAPLAMA", "K1", "FLAP ALPI10.51"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALPI 12.12 KAPLAMA", "K2", "FLAP ALPI12.12"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALPI 12.94 KAPLAMA", "K5", "FLAP ALPI12.94"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALPI 12.96 KAPLAMA", "K3", "FLAP ALPI12.96"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ALUMINYUM", "ALU", "FLAP ALUMINYUM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP AND.CEVIZ LAMINAT", "L7", "FLAP AND.CEVIZ LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP ANTRASIT LAMINAT", "L5", "FLAP ANTRASIT LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP BEJ LAMINAT", "L2", "FLAP BEJ LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP BEYAZ LAMINAT", "L1", "FLAP BEYAZ LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP BRONCE MESE KAPLAMA", "K6", "FLAP BRONCE MESE"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP KAPLAMA", "K0", "FLAP"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP KUMBEJI LAMINAT", "L3", "FLAP KUMBEJI LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP LAMINAT", "L0", "FLAP LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP SAFIR MESE LAMINAT", "L8", "FLAP S.MESE LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP VIZON LAMINAT", "L4", "FLAP VIZON LAM"),
(30, "MASA FLAP MALZEME VE RENK", "MASA FLAP YENI CEVIZ LAMINAT", "L6", "FLAP Y.CEVIZ LAM"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS E.S BOYALI", "E0", "TRAVERS E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL1013 E.S BOYALI", "E1", "TRAVERS T1013E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL1019 E.S BOYALI", "E2", "TRAVERS T1019E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL7016 E.S BOYALI", "E3", "TRAVERS T7016E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL7022 E.S BOYALI", "E4", "TRAVERS T7022E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL9005 E.S BOYALI", "E5", "TRAVERS T9005E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL9007 E.S BOYALI", "E6", "TRAVERS T9007E.S"),
(40, "MASA TRAVERS RENK", "MASA TRAVERS RAL9016 E.S BOYALI", "E7", "TRAVERS T9016E.S"),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ E.S BOYALI", "E0", "TOPUZ E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL1013 E.S BOYALI", "E1", "TOPUZ T1013E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL1019 E.S BOYALI", "E2", "TOPUZ T1019E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL7016 E.S BOYALI", "E3", "TOPUZ T7016E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL7022 E.S BOYALI", "E4", "TOPUZ T7022E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL9005 E.S BOYALI", "E5", "TOPUZ T9005E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL9007 E.S BOYALI", "E6", "TOPUZ T9007E.S "),
(50, "MASA AYAK TOPUZ BAĞLANTI RENK", "MASA AYAK TOPUZ RAL9016 E.S BOYALI", "E7", "TOPUZ T9016E.S "),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK E.S BOYALI", "E0", "AYAK E.S BOYA"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL1013 E.S BOYALI", "E1", "AYAK T1013E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL1019 E.S BOYALI", "E2", "AYAK T1019E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL7016 E.S BOYALI", "E3", "AYAK T7016E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL7022 E.S BOYALI", "E4", "AYAK T7022E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL9005 E.S BOYALI", "E5", "AYAK T9005E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL9007 E.S BOYALI", "E6", "AYAK T9007E.S"),
(60, "MASA AYAK MALZEME VE RENK", "MASA AYAK RAL9016 E.S BOYALI", "E7", "AYAK T9016E.S"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ALPI 10.43 KAPLAMA", "K4", "M.PANEL ALPI10.43"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ALPI 10.51 KAPLAMA", "K1", "M.PANEL ALPI10.51"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ALPI 12.12 KAPLAMA", "K2", "M.PANEL ALPI12.12"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ALPI 12.94 KAPLAMA", "K5", "M.PANEL ALPI12.94"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ALPI 12.96 KAPLAMA", "K3", "M.PANEL ALPI12.96"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL AND.CEVIZ LAMINAT", "L7", "M.PANEL AND.CEVIZ LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL AND.CEVIZ MYL", "M7", "M.PANEL AND.CEVIZ MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ANTRASIT LAMINAT", "L5", "M.PANEL ANTRASIT LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL ANTRASIT MYL", "M5", "M.PANEL ANTRASIT MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL BEJ LAMINAT", "L2", "M.PANEL BEJ LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL BEJ MYL", "M2", "M.PANEL BEJ MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL BEYAZ LAMINAT", "L1", "M.PANEL BEYAZ LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL BEYAZ MYL", "M1", "M.PANEL BEYAZ MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL BRONCE MESE KAPLAMA", "K6", "M.PANEL BRONCE MESE"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL KAPLAMA", "K0", "M.PANEL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL KUMBEJI LAMINAT", "L3", "M.PANEL KUMBEJI LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL KUMBEJI MYL", "M3", "M.PANEL KUMBEJI MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL LAMINAT", "L0", "M.PANEL LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL MYL", "M0", "M.PANEL MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL SAFIR MESE LAMINAT", "L8", "M.PANEL S.MESE LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL SAFIR MESE MYL", "M8", "M.PANEL S.MESE MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL VIZON LAMINAT", "L4", "M.PANEL VIZON LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL VIZON MYL", "M4", "M.PANEL VIZON MYL"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL YENI CEVIZ LAMINAT", "L6", "M.PANEL Y.CEVIZ LAM"),
(70, "MODESTY PANEL MALZEME VE RENK", "MODESTY PANEL YENI CEVIZ MYL", "M6", "M.PANEL Y.CEVIZ MYL"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SAĞ YÖNLÜ-KISA-DAR", "R.B.D", "SAĞ-KISA-DAR ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SAĞ YÖNLÜ-KISA-GENİŞ", "R.B.G", "SAĞ-KISA-GENİŞ ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SAĞ YÖNLÜ-UZUN-DAR", "R.C.D", "SAĞ-UZUN-DAR ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SAĞ YÖNLÜ-UZUN-GENİŞ", "R.C.G", "SAĞ-UZUN-GENİŞ ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SOL YÖNLÜ-KISA-DAR", "L.B.D", "SOL-KISA-DAR ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SOL YÖNLÜ-KISA-GENİŞ", "L.B.G", "SOL-KISA-GENİŞ ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SOL YÖNLÜ-UZUN-DAR", "L.C.D", "SOL-UZUN-DAR ETJ"),
(80, "ETAJER YÖN+ÖLÇÜ", "ETAJER SOL YÖNLÜ-UZUN-GENİŞ", "L.C.G", "SOL-UZUN-GENİŞ ETJ"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ALPI 10.43 KAPLAMA", "K4", "ETJ GÖVDE+ÜST TAC ALPI10.43 "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ALPI 10.51 KAPLAMA", "K1", "ETJ GÖVDE+ÜST TAC ALPI10.51 "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ALPI 12.12 KAPLAMA", "K2", "ETJ GÖVDE+ÜST TAC ALPI12.12 "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ALPI 12.94 KAPLAMA", "K5", "ETJ GÖVDE+ÜST TAC ALPI12.94 "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ALPI 12.96 KAPLAMA", "K3", "ETJ GÖVDE+ÜST TAC ALPI12.96 "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC AND.CEVIZ LAMINAT", "L7", "ETJ GÖVDE+ÜST TAC AND.CEVIZ LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC AND.CEVIZ MYL", "M7", "ETJ GÖVDE+ÜST TAC AND.CEVIZ MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ANTRASIT LAMINAT", "L5", "ETJ GÖVDE+ÜST TAC ANTRASIT LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC ANTRASIT MYL", "M5", "ETJ GÖVDE+ÜST TAC ANTRASIT MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC BEJ LAMINAT", "L2", "ETJ GÖVDE+ÜST TAC BEJ LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC BEJ MYL", "M2", "ETJ GÖVDE+ÜST TAC BEJ MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC BEYAZ LAMINAT", "L1", "ETJ GÖVDE+ÜST TAC BEYAZ LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC BEYAZ MYL", "M1", "ETJ GÖVDE+ÜST TAC BEYAZ MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC BRONCE MESE KAPLAMA", "K6", "ETJ GÖVDE+ÜST TAC BRONCE MESE "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC KAPLAMA", "K0", "ETJ GÖVDE+ÜST TAC "),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC KUMBEJI LAMINAT", "L3", "ETJ GÖVDE+ÜST TAC KUMBEJI LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC KUMBEJI MYL", "M3", "ETJ GÖVDE+ÜST TAC KUMBEJI MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC LAMINAT", "L0", "ETJ GÖVDE+ÜST TAC LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC MYL", "M0", "ETJ GÖVDE+ÜST TAC MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC SAFIR MESE LAMINAT", "L8", "ETJ GÖVDE+ÜST TAC S.MESE LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC SAFIR MESE MYL", "M8", "ETJ GÖVDE+ÜST TAC S.MESE MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC VIZON LAMINAT", "L4", "ETJ GÖVDE+ÜST TAC VIZON LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC VIZON MYL", "M4", "ETJ GÖVDE+ÜST TAC VIZON MYL"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC YENI CEVIZ LAMINAT", "L6", "ETJ GÖVDE+ÜST TAC Y.CEVIZ LAM"),
(90, "ETAJER YAN+GÖVDE+ÜST TAC MALZEME VE RENK", "ETAJER GÖVDE+ÜST TAC YENI CEVIZ MYL", "M6", "ETJ GÖVDE+ÜST TAC Y.CEVIZ MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ALPI 10.43 KAPLAMA", "K4", "KLAPA ALPI10.43 "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ALPI 10.51 KAPLAMA", "K1", "KLAPA ALPI10.51 "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ALPI 12.12 KAPLAMA", "K2", "KLAPA ALPI12.12 "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ALPI 12.94 KAPLAMA", "K5", "KLAPA ALPI12.94 "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ALPI 12.96 KAPLAMA", "K3", "KLAPA ALPI12.96 "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA AND.CEVIZ LAMINAT", "L7", "KLAPA AND.CEVIZ LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA AND.CEVIZ MYL", "M7", "KLAPA AND.CEVIZ MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ANTRASIT LAMINAT", "L5", "KLAPA ANTRASIT LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA ANTRASIT MYL", "M5", "KLAPA ANTRASIT MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA BEJ LAMINAT", "L2", "KLAPA BEJ LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA BEJ MYL", "M2", "KLAPA BEJ MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA BEYAZ LAMINAT", "L1", "KLAPA BEYAZ LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA BEYAZ MYL", "M1", "KLAPA BEYAZ MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA BRONCE MESE KAPLAMA", "K6", "KLAPA BRONCE MESE "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA KAPLAMA", "K0", "KLAPA "),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA KUMBEJI LAMINAT", "L3", "KLAPA KUMBEJI LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA KUMBEJI MYL", "M3", "KLAPA KUMBEJI MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA LAMINAT", "L0", "KLAPA LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA MYL", "M0", "KLAPA MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA SAFIR MESE LAMINAT", "L8", "KLAPA S.MESE LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA SAFIR MESE MYL", "M8", "KLAPA S.MESE MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA VIZON LAMINAT", "L4", "KLAPA VIZON LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA VIZON MYL", "M4", "KLAPA VIZON MYL"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA YENI CEVIZ LAMINAT", "L6", "KLAPA Y.CEVIZ LAM"),
(100, "ETAJER KLAPA MALZEME + RENK", "ETAJER KLAPA YENI CEVIZ MYL", "M6", "KLAPA Y.CEVIZ MYL"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP E.S BOYALI", "E0", "BOY KULP E.S BOYA"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL1013 E.S BOYALI", "E1", "BOY KULP T1013E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL1019 E.S BOYALI", "E2", "BOY KULP T1019E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL7016 E.S BOYALI", "E3", "BOY KULP T7016E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL7022 E.S BOYALI", "E4", "BOY KULP T7022E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL9005 E.S BOYALI", "E5", "BOY KULP T9005E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL9007 E.S BOYALI", "E6", "BOY KULP T9007E.S"),
(110, "ETAJER KULP MALZEME VE RENK", "ETAJER BOY KULP RAL9016 E.S BOYALI", "E7", "BOY KULP T9016E.S"),
(120, "ETAJER ÇEKMECE ADET", "ETAJER 2 ÇEKMECELİ", "2CK", "2ÇK"),
(120, "ETAJER ÇEKMECE ADET", "ETAJER 3 ÇEKMECELİ", "3CK", "3ÇK"),
(130, "ÖN KUMAS PANEL KATEGÖRİSİ", "KATEGORİ 1 ÖN KUMAŞ", "KT1", "KT1"),
(130, "ÖN KUMAS PANEL KATEGÖRİSİ", "KATEGORİ 3 ÖN KUMAŞ", "KT3", "KT3"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE02", "KT1-1", "ÖN PANEL  ERACSE02 "),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE33", "KT1-10", "ÖN PANEL  ERACSE33"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE34", "KT1-11", "ÖN PANEL  ERACSE34"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE39", "KT1-12", "ÖN PANEL  ERACSE39"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE40", "KT1-13", "ÖN PANEL  ERACSE40"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE42", "KT1-14", "ÖN PANEL  ERACSE42"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE44", "KT1-15", "ÖN PANEL  ERACSE44"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE03", "KT1-2", "ÖN PANEL  ERACSE03"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE07", "KT1-3", "ÖN PANEL  ERACSE07"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE13", "KT1-4", "ÖN PANEL  ERACSE13"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE14", "KT1-5", "ÖN PANEL  ERACSE14"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE23", "KT1-6", "ÖN PANEL  ERACSE23"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE27", "KT1-7", "ÖN PANEL  ERACSE27"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE28", "KT1-8", "ÖN PANEL  ERACSE28"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS ERACSE29", "KT1-9", "ÖN PANEL  ERACSE29"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS16", "KT3-1", "ÖN PANEL  LDS16"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS62", "KT3-10", "ÖN PANEL  LDS62"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS73", "KT3-11", "ÖN PANEL  LDS73"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS74", "KT3-12", "ÖN PANEL  LDS74"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS76", "KT3-13", "ÖN PANEL  LDS76"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS84", "KT3-14", "ÖN PANEL  LDS84"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS86", "KT3-15", "ÖN PANEL  LDS86"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS17", "KT3-2", "ÖN PANEL  LDS17"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS33", "KT3-3", "ÖN PANEL  LDS33"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS45", "KT3-4", "ÖN PANEL  LDS45"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS46", "KT3-5", "ÖN PANEL  LDS46"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS47", "KT3-6", "ÖN PANEL  LDS47"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS48", "KT3-7", "ÖN PANEL  LDS48"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS55", "KT3-8", "ÖN PANEL  LDS55"),
(140, "ÖN PANEL KUMAS RENK", "ÖN PANEL KUMAS LDS56", "KT3-9", "ÖN PANEL  LDS56"),
(150, "MASA ÖLÇÜSÜ", "L140 D70 H75 CM", "14070", "L140 D70 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L140 D80 H75 CM", "14080", "L140 D80 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L140 D90 H75 CM", "14090", "L140 D90 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L160 D70 H75 CM", "16070", "L160 D70 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L160 D80 H75 CM", "16080", "L160 D80 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L160 D90 H75 CM", "16090", "L160 D90 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L180 D70 H75 CM", "18070", "L180 D70 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L180 D80 H75 CM", "18080", "L180 D80 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L180 D90 H75 CM", "18090", "L180 D90 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L200 D70 H75 CM", "20070", "L200 D70 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L200 D80 H75 CM", "20080", "L200 D80 H75 CM"),
(150, "MASA ÖLÇÜSÜ", "L200 D90 H75 CM", "20090", "L200 D90 H75 CM"),


]

class Command(BaseCommand):
    help = "GERÇEKÇİ FOLLOW TEKİL MASA SETUP (Yeni Model Yapısına Uyumlu)"

    def handle(self, *args, **options):
        # 1. Ürün ailesi ve ürün oluşturuluyor.
        family, _ = ProductFamily.objects.get_or_create(
            name="Operasyonel Tekil Masa"
        )

        product, created_prod = Product.objects.get_or_create(
            name="FOLLOW TEKİL MASA",
            family=family,
            defaults={
                "code": "30.FOL",
                "variant_code": "FOL",
                "variant_description": "FOLLOW TEKİL MASA",
                "base_price": 450,
                "currency": "EUR",
                "variant_order": 1,
            }
        )
        if created_prod:
            self.stdout.write(self.style.SUCCESS(f"Yeni ürün oluşturuldu: {product.name}"))
        else:
            self.stdout.write(f"Ürün zaten var: {product.name}")

        # 2. Verileri gruplayarak SpecificationType, SpecOption, SpecificationOption ve ProductSpecification oluşturuluyor.
        specs_dict = defaultdict(lambda: defaultdict(list))

        for row in BEEWORK_DATA:
            sira_no, spec_name, option_name, variant_code, variant_description = row
            specs_dict[sira_no][spec_name].append({
                "option_name": option_name,
                "variant_code": variant_code,
                "variant_description": variant_description
            })

        for sira_no in sorted(specs_dict.keys()):
            for spec_name, option_list in specs_dict[sira_no].items():
                spec_type, created = SpecificationType.objects.get_or_create(
                    name=spec_name,
                    defaults={
                        "group": "BEEWORK",
                        "is_required": True,
                        "allow_multiple": False,
                        "variant_order": sira_no,
                        "display_order": sira_no,
                        "multiplier": 1.00
                    }
                )
                if created:
                    self.stdout.write(f"[SpecType] Yeni oluşturuldu: {spec_name}")
                else:
                    self.stdout.write(f"[SpecType] Zaten vardı: {spec_name}")

                ProductSpecification.objects.get_or_create(
                    product=product,
                    spec_type=spec_type,
                    defaults={
                        "is_required": True,
                        "allow_multiple": False,
                        "variant_order": sira_no,
                        "display_order": sira_no
                    }
                )

                for idx, item in enumerate(option_list, start=1):
                    opt_name = item["option_name"]
                    var_code = item["variant_code"]
                    var_desc = item["variant_description"]

                    spec_option, created_opt = SpecOption.objects.get_or_create(
                        spec_type=spec_type,
                        name=opt_name,
                        defaults={
                            "variant_code": var_code,
                            "variant_description": var_desc,
                            "image": None,
                            "price_delta": 0.00,
                            "is_default": False,
                            "display_order": idx
                        }
                    )
                    if created_opt:
                        self.stdout.write(f"  → [SpecOption] {opt_name} eklendi.")
                    else:
                        self.stdout.write(f"  → [SpecOption] {opt_name} zaten vardı.")

                    SpecificationOption.objects.get_or_create(
                        product=product,
                        spec_type=spec_type,
                        option=spec_option,
                        defaults={
                            "is_default": False,
                            "display_order": idx
                        }
                    )

                self.stdout.write(self.style.SUCCESS(f"→ {spec_name} eklendi ve eşleşmeler tamamlandı"))

        self.stdout.write(self.style.SUCCESS("Tüm özellikler, seçenekler ve eşlemeler oluşturuldu."))
