# Generated by Django 5.0.8 on 2025-04-29 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_detail_no', models.CharField(max_length=50, unique=True)),
                ('belge_no', models.CharField(max_length=20)),
                ('tedarikci_kod', models.CharField(max_length=20)),
                ('tedarikci_ad', models.CharField(max_length=100)),
                ('belge_tarih', models.DateField()),
                ('teslim_tarih', models.DateField(blank=True, null=True)),
                ('belge_status', models.CharField(max_length=10)),
                ('belge_aciklamasi', models.TextField(blank=True, null=True)),
                ('sevk_adres', models.TextField(blank=True, null=True)),
                ('kalem_grup', models.CharField(blank=True, max_length=100, null=True)),
                ('satir_status', models.CharField(max_length=10)),
                ('satir_no', models.IntegerField()),
                ('kalem_kod', models.CharField(max_length=50)),
                ('kalem_tanimi', models.CharField(max_length=255)),
                ('birim', models.CharField(max_length=20)),
                ('sip_miktar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('detay_kur', models.DecimalField(decimal_places=4, max_digits=18)),
                ('detay_doviz', models.CharField(max_length=10)),
                ('net_fiyat_dpb', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referans_teklifler', models.JSONField(blank=True, null=True)),
                ('teklif_fiyatlari_json', models.JSONField(blank=True, null=True)),
                ('teklif_fiyatlari_list', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchase Comparison',
                'verbose_name_plural': 'Purchase Comparisons',
                'db_table': 'purchase_comparisons',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.IntegerField(unique=True)),
                ('doc_num', models.CharField(max_length=20)),
                ('card_code', models.CharField(max_length=20)),
                ('card_name', models.CharField(max_length=100)),
                ('doc_date', models.DateField()),
                ('doc_due_date', models.DateField(blank=True, null=True)),
                ('wdd_status', models.CharField(max_length=5)),
                ('doc_status', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_no', models.CharField(max_length=20)),
                ('uniq_detail_no', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('onay', 'Onay'), ('kismi_onay', 'Kısmi Onay'), ('red', 'Red'), ('onay_iptal', 'Onay İptal')], max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('satir_detay_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Approval',
                'verbose_name_plural': 'Purchase Approvals',
                'db_table': 'purchase_approvals',
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.IntegerField()),
                ('doc_num', models.CharField(max_length=20)),
                ('card_code', models.CharField(max_length=20)),
                ('card_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('line_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchase Quote',
                'verbose_name_plural': 'Purchase Quotes',
                'db_table': 'purchase_quotes',
                'unique_together': {('doc_num', 'item_code', 'line_num')},
            },
        ),
    ]
