# Generated by Django 5.0.8 on 2025-05-24 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('file_id', models.BigIntegerField(db_index=True, editable=False, unique=True)),
                ('path', models.TextField(help_text='Dosyanın göreli yoludur.')),
                ('is_dir', models.BooleanField(default=False)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('ext', models.CharField(blank=True, max_length=10)),
                ('is_image', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('path', 'name')},
            },
        ),
    ]
