# Generated by Django 5.0.8 on 2025-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharehub_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='path',
            field=models.TextField(help_text='Göreli dizin yoludur.'),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
