# Generated by Django 4.2.7 on 2024-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numara', models.IntegerField(primary_key=True, serialize=False)),
                ('baslangic_tarihi', models.DateField()),
                ('isleyen', models.CharField(max_length=100)),
                ('tayin_eden', models.CharField(max_length=100)),
                ('aktivite', models.CharField(blank=True, max_length=50, null=True)),
                ('tur', models.CharField(blank=True, max_length=50, null=True)),
                ('konu', models.CharField(blank=True, max_length=100, null=True)),
                ('muhatap_kod', models.CharField(blank=True, max_length=20, null=True)),
                ('muhatap_ad', models.CharField(blank=True, max_length=100, null=True)),
                ('durum', models.CharField(blank=True, max_length=100, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('icerik', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aktivite',
                'verbose_name_plural': 'Aktiviteler',
            },
        ),
    ]
