# Generated by Django 4.2.7 on 2024-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='baslama_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='bitis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
