# Generated by Django 4.2.7 on 2024-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_baslama_saati_activity_bitis_saati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='baslangic_tarihi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='bitis_tarihi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
