# Generated by Django 4.2.7 on 2024-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
