# Generated by Django 5.0.8 on 2025-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-create_datetime', '-numara'], 'verbose_name': 'Aktivite', 'verbose_name_plural': 'Aktiviteler'},
        ),
        migrations.AddField(
            model_name='activity',
            name='create_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
