# Generated by Django 5.0.8 on 2025-04-02 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('name', models.CharField(max_length=100, verbose_name='Aile Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_family/', verbose_name='Görsel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': '02- Ürün Ailesi',
                'verbose_name_plural': '02- Ürün Aileleri',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli')),
                ('variant_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Varyant Kod Şablonu')),
                ('variant_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant Açıklama Şablonu')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Temel Fiyat')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Para Birimi')),
                ('variant_order', models.PositiveIntegerField(default=1, verbose_name='Varyant Sırası')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productconfigv2.productfamily', verbose_name='Ürün Ailesi')),
            ],
            options={
                'verbose_name': '03- Ürün',
                'verbose_name_plural': '03- Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('rule_type', models.CharField(choices=[('deny', 'Geçersiz Kıl'), ('allow', 'Geçerli Kıl')], max_length=5, verbose_name='Kural Tipi')),
                ('name', models.CharField(max_length=150, verbose_name='Kural Adı')),
                ('conditions', models.JSONField(verbose_name='Koşullar')),
                ('actions', models.JSONField(verbose_name='Aksiyonlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='productconfigv2.productfamily', verbose_name='Ürün Ailesi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': '10- Kural',
                'verbose_name_plural': '10- Kurallar',
            },
        ),
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('name', models.CharField(max_length=100, verbose_name='Özellik Tipi Adı')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özellik Grubu')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Çoklu Seçim İzinli mi?')),
                ('variant_order', models.PositiveIntegerField(default=1, verbose_name='Varyant Sırası')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Görsel Sıra')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Fiyat Çarpanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': '04- Özellik Tipi',
                'verbose_name_plural': '04- Özellik Tipleri',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('name', models.CharField(max_length=100, verbose_name='Seçenek Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spec_options/', verbose_name='Görsel')),
                ('variant_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Varyant Kod Parçası')),
                ('variant_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Varyant Açıklama Parçası')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat Etkisi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan mı?')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Görsel Sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='productconfigv2.specificationtype', verbose_name='Bağlı Olduğu Özellik Tipi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': '05- Özellik Seçeneği',
                'verbose_name_plural': '05- Özellik Seçenekleri',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('new_variant_code', models.CharField(max_length=100, unique=True, verbose_name='Yeni Varyant Kodu')),
                ('new_variant_description', models.CharField(max_length=500, verbose_name='Yeni Varyant Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_images/', verbose_name='Görsel')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Fiyat')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Para Birimi')),
                ('is_generated', models.BooleanField(default=True, verbose_name='Otomatik Oluşturuldu mu?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='productconfigv2.product', verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': '08- Varyant',
                'verbose_name_plural': '08- Varyantlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Çoklu Seçim İzinli mi?')),
                ('variant_order', models.PositiveIntegerField(default=1, verbose_name='Varyant Sırası (Ürün Bazlı)')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Görsel Sıra (Ürün Bazlı)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='productconfigv2.product', verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='productconfigv2.specificationtype', verbose_name='Özellik Tipi')),
            ],
            options={
                'verbose_name': '06- Ürün Özellik İlişkisi',
                'verbose_name_plural': '06- Ürün Özellik İlişkileri',
                'ordering': ['variant_order'],
                'unique_together': {('product', 'spec_type')},
            },
        ),
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Seçenek mi?')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Görsel Sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_options', to='productconfigv2.product', verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_options', to='productconfigv2.specificationtype', verbose_name='Özellik Tipi')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_options', to='productconfigv2.specoption', verbose_name='Seçenek')),
            ],
            options={
                'verbose_name': '07- Ürün Özellik Seçeneği',
                'verbose_name_plural': '07- Ürün Özellik Seçenekleri',
                'ordering': ['display_order'],
                'unique_together': {('product', 'spec_type', 'option')},
            },
        ),
        migrations.CreateModel(
            name='VariantSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productconfigv2.specoption', verbose_name='Seçilen Seçenek')),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productconfigv2.specificationtype', verbose_name='Özellik Tipi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='productconfigv2.variant', verbose_name='Varyant')),
            ],
            options={
                'verbose_name': '09- Varyant Seçimi',
                'verbose_name_plural': '09- Varyant Seçimleri',
                'unique_together': {('variant', 'spec_type')},
            },
        ),
    ]
