# Generated by Django 5.0.8 on 2025-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specoption',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Referans Fiyat Kodu (55'li Kod Parçası)"),
        ),
    ]
