# Generated by Django 5.0.8 on 2025-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0002_specoption_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_product_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Referans Ürün Kodu (55'li)"),
        ),
    ]
