# Generated by Django 5.0.8 on 2025-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0003_product_reference_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name="Referans Kodu (55'li)"),
        ),
    ]
