# Generated by Django 5.0.8 on 2025-09-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0004_variant_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Proje Adı'),
        ),
    ]
