# Generated by Django 5.0.8 on 2025-09-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0005_variant_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='project_name_search',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
