# Generated by Django 5.0.8 on 2025-09-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productconfigv2', '0006_variant_project_name_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='project_name_search',
        ),
    ]
