# Generated by Django 4.2.7 on 2024-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satici', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satıcı')),
                ('grup', models.CharField(max_length=50, verbose_name='Grup')),
                ('muhatap_kod', models.CharField(max_length=50, unique=True, verbose_name='Muhatap Kod')),
                ('avans_kod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Avans Kod')),
                ('muhatap_ad', models.CharField(max_length=255, verbose_name='Muhatap Adı')),
                ('tahsilat', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Tahsilat')),
                ('bakiye', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Bakiye')),
                ('acik_teslimat', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Açık Teslimat')),
                ('acik_siparis', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Açık Sipariş')),
                ('toplam_risk', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Toplam Risk')),
                ('avans_bakiye', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Avans Bakiye')),
            ],
            options={
                'verbose_name': 'Toplam Risk Raporu',
                'verbose_name_plural': 'Toplam Risk Raporları',
            },
        ),
    ]
