# Generated by Django 4.2.7 on 2024-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalrisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalriskreport',
            name='tahsilat',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tahsilat'),
        ),
        migrations.AlterField(
            model_name='totalriskreport',
            name='toplam_risk',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Toplam Risk'),
        ),
    ]
