# Generated by Django 4.2.7 on 2024-03-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalrisk', '0002_alter_totalriskreport_tahsilat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalriskreport',
            name='tahsilat',
        ),
    ]
