# Generated by Django 4.2.7 on 2024-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('depo_kodu', models.CharField(db_index=True, max_length=50, verbose_name='Depo Kodu')),
                ('kalem_grup_ad', models.CharField(max_length=255, verbose_name='Kalem Grup Adı')),
                ('stok_kalem', models.BooleanField(default=False, verbose_name='Stok Kalem')),
                ('satis_kalem', models.BooleanField(default=False, verbose_name='Satış Kalem')),
                ('satinalma_kalem', models.BooleanField(default=False, verbose_name='Satınalma Kalem')),
                ('yapay_kalem', models.BooleanField(default=False, verbose_name='Yapay Kalem')),
                ('kalem_kod', models.CharField(db_index=True, max_length=50, verbose_name='Kalem Kod')),
                ('kalem_tanim', models.CharField(max_length=255, verbose_name='Kalem Tanım')),
                ('stok_olcu_birim', models.CharField(max_length=50, verbose_name='Stok Ölçü Birim')),
                ('depo_stok', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depo Stok')),
                ('siparis_edilen_miktar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sipariş Edilen Miktar')),
                ('son_satinalma_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Son Satınalma Fiyat')),
                ('son_satinalma_fatura_tarih', models.DateField(default='1900-01-01', verbose_name='Son Satınalma Fatura Tarihi')),
                ('verilen_siparisler', models.TextField(default='Yok', verbose_name='Verilen Siparişler')),
            ],
            options={
                'verbose_name': 'Hammadde Depo Stok Durumu',
                'verbose_name_plural': 'Hammadde Depo Stok Durumları',
                'ordering': ['kalem_kod'],
            },
        ),
    ]
