# Generated by Django 4.2.7 on 2024-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='depo_kodu',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Depo Kodu'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='depo_stok',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Depo Stok'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_grup_ad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kalem Grup Adı'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_kod',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Kalem Kod'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_tanim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kalem Tanım'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='satinalma_kalem',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Satınalma Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='satis_kalem',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Satış Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='siparis_edilen_miktar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sipariş Edilen Miktar'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='son_satinalma_fatura_tarih',
            field=models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Son Satınalma Fatura Tarihi'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='son_satinalma_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Son Satınalma Fiyat'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='stok_kalem',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Stok Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='stok_olcu_birim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stok Ölçü Birim'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='verilen_siparisler',
            field=models.TextField(blank=True, default='Yok', null=True, verbose_name='Verilen Siparişler'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='yapay_kalem',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yapay Kalem'),
        ),
    ]
