# Generated by Django 4.2.7 on 2024-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0002_alter_rawmaterialwarehousestock_depo_kodu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='depo_kodu',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Depo Kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='depo_stok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depo Stok'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_grup_ad',
            field=models.CharField(default=1, max_length=255, verbose_name='Kalem Grup Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_kod',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Kalem Kod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_tanim',
            field=models.CharField(default=1, max_length=255, verbose_name='Kalem Tanım'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='satinalma_kalem',
            field=models.BooleanField(default=False, verbose_name='Satınalma Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='satis_kalem',
            field=models.BooleanField(default=False, verbose_name='Satış Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='siparis_edilen_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sipariş Edilen Miktar'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='son_satinalma_fatura_tarih',
            field=models.DateField(default='1900-01-01', verbose_name='Son Satınalma Fatura Tarihi'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='son_satinalma_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Son Satınalma Fiyat'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='stok_kalem',
            field=models.BooleanField(default=False, verbose_name='Stok Kalem'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='stok_olcu_birim',
            field=models.CharField(default=1, max_length=50, verbose_name='Stok Ölçü Birim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='verilen_siparisler',
            field=models.TextField(default='Yok', verbose_name='Verilen Siparişler'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='yapay_kalem',
            field=models.BooleanField(default=False, verbose_name='Yapay Kalem'),
        ),
    ]
