# Generated by Django 4.2.7 on 2024-07-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0003_alter_rawmaterialwarehousestock_depo_kodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialwarehousestock',
            name='secili',
            field=models.BooleanField(default=False, verbose_name='Seçili'),
        ),
    ]
