# Generated by Django 4.2.7 on 2024-07-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0004_rawmaterialwarehousestock_secili'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialwarehousestock',
            name='secili',
        ),
    ]
