# Generated by Django 4.2.7 on 2024-07-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0005_remove_rawmaterialwarehousestock_secili'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialwarehousestock',
            name='secili',
            field=models.BooleanField(default=False, verbose_name='Seçili'),
        ),
    ]
