# Generated by Django 4.2.7 on 2024-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0006_rawmaterialwarehousestock_secili'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialwarehousestock',
            name='hide_zero_stock',
            field=models.BooleanField(default=False, verbose_name='Sıfır Stoklu Satırları Gizle'),
        ),
    ]
