# Generated by Django 4.2.7 on 2024-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterialwarehousestock', '0007_rawmaterialwarehousestock_hide_zero_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialwarehousestock',
            name='kalem_kod',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Kalem Kod'),
        ),
    ]
