# Generated by Django 5.0.8 on 2025-08-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formforgeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Metin'), ('number', 'Sayı'), ('email', 'E-posta'), ('textarea', 'Metin Alanı'), ('singleselect', 'Tekli Seçim'), ('multiselect', 'Çoklu Seçim'), ('checkbox', 'Onay Kutusu'), ('radio', 'Radyo Düğmesi'), ('date', 'Tarih')], max_length=20, verbose_name='Alan Tipi'),
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='formforgeapi.formfield', verbose_name='Form Alanı')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
