# Generated by Django 5.0.8 on 2025-08-06 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formforgeapi', '0002_alter_formfield_field_type_formfieldoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='form',
            name='parent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='formforgeapi.form', verbose_name='Ana Form'),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('PUBLISHED', 'Dağıtımda'), ('ARCHIVED', 'Arşivlenmiş')], default='PUBLISHED', max_length=10, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='form',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon'),
        ),
    ]
