# Generated by Django 5.0.8 on 2025-08-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formforgeapi', '0003_alter_form_options_form_parent_form_form_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Versiyon'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='formforgeapi.formsubmission', verbose_name='Ana Gönderim'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon'),
        ),
    ]
