# Generated by Django 5.0.8 on 2025-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formforgeapi', '0004_formsubmission_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Metin'), ('number', 'Sayı'), ('email', 'E-posta'), ('textarea', 'Metin Alanı'), ('checkbox', 'Onay Kutusu'), ('date', 'Tarih'), ('phone', 'Telefon Numarası'), ('url', 'Web Adresi (URL)'), ('singleselect', 'Tekli Seçim'), ('multiselect', 'Çoklu Seçim'), ('radio', 'Radyo Düğmesi'), ('yesno', 'Evet/Hayır'), ('datetime', 'Tarih ve Saat'), ('time', 'Saat'), ('daterange', 'Tarih Aralığı'), ('fileupload', 'Dosya Yükleme'), ('imageupload', 'Resim Yükleme'), ('currency', 'Para Birimi'), ('percentage', 'Yüzde'), ('rating', 'Derecelendirme'), ('signature', 'Elektronik İmza'), ('userpicker', 'Kullanıcı Seçimi'), ('departmentpicker', 'Departman Seçimi'), ('autocomplete', 'Otomatik Tamamlama'), ('predefined_select', 'Ön Tanımlı Liste'), ('heading', 'Başlık'), ('paragraph', 'Açıklama Metni'), ('separator', 'Ayıraç'), ('calculated', 'Hesaplanmış Alan'), ('hidden', 'Gizli Alan')], max_length=30, verbose_name='Alan Tipi'),
        ),
    ]
