# Generated by Django 5.0.8 on 2025-08-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formforgeapi', '0006_alter_formsubmission_parent_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='formforgeapi.formsubmission', verbose_name='Ana Gönderim'),
        ),
    ]
