# Generated by Django 4.2.7 on 2024-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('item_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=25, null=True)),
                ('currency', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('picture_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
