# Generated by Django 5.0.8 on 2025-06-17 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBudgetEURModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('satici', models.CharField(db_index=True, max_length=150, verbose_name='Satıcı')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('toplam_gercek_eur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('toplam_hedef_eur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('toplam_iptal_eur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('toplam_elle_kapanan_eur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kapali_sip_list', models.TextField(blank=True, null=True, verbose_name='Kapalı/İptal Siparişler JSON')),
            ],
            options={
                'verbose_name': 'Satış Bütçesi (EUR)',
                'verbose_name_plural': 'Satış Bütçeleri (EUR)',
                'unique_together': {('satici', 'yil')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesBudgetEUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('ay', models.PositiveSmallIntegerField(verbose_name='Ay (1-12)')),
                ('gercek_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hedef_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aylik_veriler', to='salesbudgeteur.salesbudgeteurmodel')),
            ],
            options={
                'verbose_name': 'Aylık Satış Verisi (EUR)',
                'verbose_name_plural': 'Aylık Satış Verileri (EUR)',
                'unique_together': {('parent', 'ay')},
            },
        ),
    ]
