# Generated by Django 5.0.8 on 2025-04-20 12:10

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cari_ad', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('iban', models.TextField(blank=True, null=True)),
                ('odemekosulu', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('current_balance', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('monthly_balances', models.JSONField(null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['monthly_balances'], name='monthly_balances_gin_tuna'), models.Index(fields=['current_balance', 'cari_kod'], name='curr_bal_cari_kod_idx_tuna')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(db_index=True, max_length=100)),
                ('cari_ad', models.CharField(db_index=True, max_length=200)),
                ('belge_tarih', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('belge_no', models.IntegerField(db_index=True)),
                ('iban', models.TextField(blank=True, null=True)),
                ('odemekosulu', models.CharField(max_length=100)),
                ('borc', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('alacak', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('is_buffer', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['belge_tarih'],
                'indexes': [models.Index(fields=['cari_kod', 'belge_tarih'], name='tunainssupp_cari_ko_dd4c05_idx'), models.Index(fields=['cari_kod', 'belge_no'], name='tunainssupp_cari_ko_ba4f20_idx'), models.Index(fields=['borc', 'alacak'], name='tunainssupp_borc_564136_idx'), models.Index(fields=['is_buffer', 'belge_tarih'], name='tunainssupp_is_buff_19fa2e_idx')],
            },
        ),
    ]
