# Generated by Django 5.0.8 on 2024-10-21 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sipariş Numarası')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Müşteri Adı')),
                ('order_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Sipariş Tarihi')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Sevk Tarihi')),
                ('planned_dates', models.JSONField(blank=True, default=list, null=True, verbose_name='Planlanan Tarihler')),
                ('planned_date_real', models.DateField(blank=True, null=True, verbose_name='Gerçek Planlanan Tarih')),
                ('planned_date_mirror', models.DateField(blank=True, null=True, verbose_name='Planlanan Tarih Aynası')),
                ('planned_date_week', models.IntegerField(blank=True, null=True, verbose_name='Planlanan Tarih Haftası')),
                ('sales_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satış Temsilcisi')),
                ('shipment_details', models.TextField(blank=True, null=True, verbose_name='Sevk Detayları')),
                ('shipment_notes', models.TextField(blank=True, null=True, verbose_name='Sevk Notları')),
                ('order_status', models.CharField(choices=[('Açık', 'Açık'), ('Kapalı', 'Kapalı')], default='Açık', max_length=10, verbose_name='Sipariş Durumu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
