# Generated by Django 5.0.8 on 2024-11-02 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipweekplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='selected_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Seçilen Renk'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MusteriAd'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='order_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='SiparisTarihi'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SiparisNo'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='order_status',
            field=models.CharField(choices=[('Açık', 'Açık'), ('Kapalı', 'Kapalı')], default='Açık', max_length=10, verbose_name='Statu'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='planned_date_mirror',
            field=models.DateField(blank=True, null=True, verbose_name='PlanlananTarih'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='planned_date_real',
            field=models.DateField(blank=True, null=True, verbose_name='GercekPlanlananTarih'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='planned_date_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='PlanHaftasi'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='planned_dates',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='PlanlananTarihler'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='sales_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Satici'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='SevkTarihi'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='shipment_details',
            field=models.TextField(blank=True, null=True, verbose_name='SevkDetaylari'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='shipment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='SevkNotlari'),
        ),
    ]
