# Generated by Django 5.0.8 on 2024-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipweekplanner', '0002_shipmentorder_selected_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentorder',
            name='order_status',
            field=models.CharField(choices=[('Acik', 'Acik'), ('Kapali', 'Kapali')], default='Acik', max_length=10, verbose_name='Statu'),
        ),
    ]
