# Generated by Django 5.0.8 on 2025-05-15 14:51

import django.contrib.postgres.indexes
import logo_supplier_receivables_aging.models.base
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAgingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('cari_kod', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cari Kod')),
                ('cari_ad', models.CharField(db_index=True, max_length=255, verbose_name='Cari Ad')),
                ('guncel_bakiye', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Güncel Bakiye')),
                ('aylik_kalan_alacak', models.JSONField(null=True, verbose_name='Aylık Kalan Alacaklar')),
            ],
            options={
                'verbose_name': 'Tedarikçi Özet Yaşlandırma',
                'verbose_name_plural': 'Tedarikçi Özet Yaşlandırmalar',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['aylik_kalan_alacak'], name='aylik_kalan_alacak_gin'), models.Index(fields=['guncel_bakiye', 'cari_kod'], name='guncel_bakiye_cari_kod_idx')],
            },
            bases=(models.Model, logo_supplier_receivables_aging.models.base.DecimalFieldMixin),
        ),
        migrations.CreateModel(
            name='SupplierRawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('cari_kod', models.CharField(max_length=64, verbose_name='Cari Kod')),
                ('cari_ad', models.CharField(max_length=255, verbose_name='Cari Ad')),
                ('ay', models.PositiveSmallIntegerField(verbose_name='Ay')),
                ('yil', models.PositiveIntegerField(verbose_name='Yıl')),
                ('borc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Borç')),
                ('alacak', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Alacak')),
            ],
            options={
                'verbose_name': 'Tedarikçi Ham İşlem',
                'verbose_name_plural': 'Tedarikçi Ham İşlemler',
                'indexes': [models.Index(fields=['cari_kod', 'yil', 'ay'], name='logo_suppli_cari_ko_9797fe_idx')],
                'unique_together': {('cari_kod', 'ay', 'yil')},
            },
            bases=(models.Model, logo_supplier_receivables_aging.models.base.DecimalFieldMixin),
        ),
    ]
