// frontend/src/redux/actions/salesbudget/actionTypes.js
// src/redux/actions/actionTypes.js
export const FETCH_LOCAL_SALES_BUDGET_REQUEST = 'FETCH_LOCAL_SALES_BUDGET_REQUEST';
export const FETCH_LOCAL_SALES_BUDGET_SUCCESS = 'FETCH_LOCAL_SALES_BUDGET_SUCCESS';
export const FETCH_LOCAL_SALES_BUDGET_FAILURE = 'FETCH_LOCAL_SALES_BUDGET_FAILURE';

// HANA Sales Budget için sabitler
export const FETCH_HANA_SALES_BUDGET_REQUEST = 'FETCH_HANA_SALES_BUDGET_REQUEST';
export const FETCH_HANA_SALES_BUDGET_SUCCESS = 'FETCH_HANA_SALES_BUDGET_SUCCESS';
export const FETCH_HANA_SALES_BUDGET_FAILURE = 'FETCH_HANA_SALES_BUDGET_FAILURE';
