// frontend/src/components/BomCostManager/redux/types.js

// BOM Cost Action Types
export const FETCH_BOM_COST_REQUEST = 'FETCH_BOM_COST_REQUEST';
export const FETCH_BOM_COST_SUCCESS = 'FETCH_BOM_COST_SUCCESS';
export const FETCH_BOM_COST_FAILURE = 'FETCH_BOM_COST_FAILURE';

export const UPDATE_BOM_COMPONENT_REQUEST = 'UPDATE_BOM_COMPONENT_REQUEST';
export const UPDATE_BOM_COMPONENT_SUCCESS = 'UPDATE_BOM_COMPONENT_SUCCESS';
export const UPDATE_BOM_COMPONENT_FAILURE = 'UPDATE_BOM_COMPONENT_FAILURE';

// Product Action Types
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAILURE = 'FETCH_PRODUCT_DETAILS_FAILURE';
