# Generated by Django 5.0.8 on 2024-10-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kodu', models.CharField(db_index=True, max_length=50)),
                ('cari_aciklamasi', models.CharField(max_length=255)),
                ('bakiye_borc', models.FloatField()),
                ('bakiye_alacak', models.FloatField()),
            ],
            options={
                'verbose_name': 'Supplier Balance',
                'verbose_name_plural': 'Supplier Balances',
                'db_table': 'supplier_balance',
                'indexes': [models.Index(fields=['cari_kodu'], name='supplier_ba_cari_ko_b7adae_idx')],
            },
        ),
    ]
