# Generated by Django 4.2.7 on 2024-05-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docarchivev2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
