# Generated by Django 5.0.8 on 2025-02-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('mail_type', models.CharField(choices=[('NEW_CUSTOMER_FORM', 'Yeni Müşteri Formu'), ('SUPPORT', 'Destek'), ('NOTIFICATION', 'Bildirim')], max_length=50, verbose_name='Mail Tipi')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu')),
                ('recipients', models.JSONField(help_text='Mail alıcılarının listesi', verbose_name='Alıcılar')),
                ('sender', models.EmailField(max_length=254, verbose_name='Gönderen')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SENDING', 'Gönderiliyor'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('created_by_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Oluşturan Kullanıcı Email')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Gönderim Tarihi')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='Ek Var Mı?')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlişkili Nesne Tipi')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='İlişkili Nesne ID')),
                ('created_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mails', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Mail Logu',
                'verbose_name_plural': 'Mail Logları',
                'indexes': [models.Index(fields=['mail_type', 'status'], name='mailservice_mail_ty_24a789_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='mailservice_related_bfd984_idx'), models.Index(fields=['created_by_email'], name='mailservice_created_acd29a_idx'), models.Index(fields=['created_by_id'], name='mailservice_created_42126e_idx')],
            },
        ),
    ]
