# Generated by Django 5.0.8 on 2025-06-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Görev adı (örn: export_customer_balance)', max_length=100, unique=True)),
                ('function_path', models.CharField(help_text='Görev fonksiyonunun Python import yolu (örn: reports.tasks.export_balance)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Görevin ne yaptığına dair açıklama')),
                ('is_active', models.BooleanField(default=True, help_text='Bu görev planlamaya açık mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Görev Tanımı',
                'verbose_name_plural': 'Görev Tanımları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Görevin kolay tanınabilir adı', max_length=150, unique=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Göreve gönderilecek parametreler')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Sistem yöneticisi notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crontab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='taskorchestrator.taskdefinition')),
            ],
            options={
                'verbose_name': 'Zamanlanmış Görev',
                'verbose_name_plural': 'Zamanlanmış Görevler',
                'ordering': ['-enabled', 'name'],
            },
        ),
    ]
