# Generated by Django 4.2.7 on 2024-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belge_no', models.CharField(max_length=50, unique=True, verbose_name='Belge Numarası')),
                ('satici', models.CharField(max_length=100, verbose_name='Satıcı')),
                ('belge_tarih', models.DateField(verbose_name='Belge Tarihi')),
                ('teslim_tarih', models.DateField(verbose_name='Teslim Tarihi')),
                ('belge_onay', models.CharField(max_length=50, verbose_name='Belge Onayı')),
                ('belge_durum', models.CharField(max_length=50, verbose_name='Belge Durumu')),
                ('musteri_kod', models.CharField(max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_ad', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('satis_tipi', models.CharField(max_length=50, verbose_name='Satış Tipi')),
                ('net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Tutar YPB')),
                ('acik_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Açık Net Tutar YPB')),
                ('acik_net_tutar_spb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Açık Net Tutar SPB')),
                ('girsberger_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Girsberger Net Tutar YPB')),
                ('mamul_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mamul Net Tutar YPB')),
                ('ticari_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticari Net Tutar YPB')),
                ('nakliye_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nakliye Net Tutar YPB')),
                ('montaj_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montaj Net Tutar YPB')),
            ],
            options={
                'verbose_name': 'Belge Özeti',
                'verbose_name_plural': 'Belge Özetleri',
            },
        ),
        migrations.CreateModel(
            name='OpenOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniq_detail_no', models.CharField(max_length=100, unique=True, verbose_name='Benzersiz Detay Numarası')),
                ('belge_no', models.CharField(max_length=50, verbose_name='Belge Numarası')),
                ('satici', models.CharField(max_length=100, verbose_name='Satıcı')),
                ('belge_tarih', models.DateField(verbose_name='Belge Tarihi')),
                ('teslim_tarih', models.DateField(verbose_name='Teslim Tarihi')),
                ('belge_onay', models.CharField(max_length=50, verbose_name='Belge Onay')),
                ('belge_durum', models.CharField(max_length=50, verbose_name='Belge Durumu')),
                ('musteri_kod', models.CharField(max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_ad', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('satis_tipi', models.CharField(max_length=50, verbose_name='Satış Tipi')),
                ('kalem_grup', models.CharField(max_length=100, verbose_name='Kalem Grubu')),
                ('satir_durum', models.CharField(max_length=50, verbose_name='Satır Durumu')),
                ('kalem_kod', models.CharField(max_length=50, verbose_name='Kalem Kodu')),
                ('kalem_tanimi', models.CharField(max_length=200, verbose_name='Kalem Tanımı')),
                ('birim', models.CharField(max_length=50, verbose_name='Birim')),
                ('siparis_miktari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sipariş Miktarı')),
                ('sevk_miktari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sevk Miktarı')),
                ('kalan_miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kalan Miktar')),
                ('liste_fiyat_dpb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liste Fiyatı DPB')),
                ('detay_kur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Detay Kur')),
                ('detay_doviz', models.CharField(max_length=10, verbose_name='Detay Döviz')),
                ('iskonto_oran', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='İskonto Oranı')),
                ('net_fiyat_dpb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Fiyat DPB')),
                ('net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Tutar YPB')),
                ('acik_net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Açık Net Tutar YPB')),
                ('acik_net_tutar_spb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Açık Net Tutar SPB')),
                ('girsberger_net_tutar_ypb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Girsberger Net Tutar YPB')),
                ('mamul_net_tutar_ypb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mamul Net Tutar YPB')),
                ('ticari_net_tutar_ypb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ticari Net Tutar YPB')),
                ('nakliye_net_tutar_ypb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nakliye Net Tutar YPB')),
                ('montaj_net_tutar_ypb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montaj Net Tutar YPB')),
            ],
            options={
                'verbose_name': 'Açık Sipariş Detayı',
                'verbose_name_plural': 'Açık Sipariş Detayları',
            },
        ),
    ]
