# Generated by Django 4.2.7 on 2024-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openorderdetail',
            name='acik_net_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Açık Net Tutar SPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='acik_net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Açık Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='detay_kur',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Detay Kur'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='girsberger_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Girsberger Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='iskonto_oran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İskonto Oranı'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='kalan_miktar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kalan Miktar'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='liste_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Liste Fiyatı DPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='mamul_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Mamul Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='montaj_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Montaj Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='nakliye_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Nakliye Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='net_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Fiyat DPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Tutar YPB'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='sevk_miktari',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sevk Miktarı'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='siparis_miktari',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sipariş Miktarı'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='ticari_net_tutar_ypb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Ticari Net Tutar YPB'),
        ),
    ]
