# Generated by Django 4.2.7 on 2024-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0002_alter_openorderdetail_acik_net_tutar_spb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openorderdetail',
            name='belge_tarih',
            field=models.DateTimeField(verbose_name='Belge Tarihi'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='teslim_tarih',
            field=models.DateTimeField(verbose_name='Teslim Tarihi'),
        ),
    ]
