# Generated by Django 4.2.7 on 2024-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0004_alter_openorderdetail_belge_tarih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Belge Tarihi'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='teslim_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='belge_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Belge Tarihi'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='teslim_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
    ]
