# Generated by Django 4.2.7 on 2024-05-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0005_alter_documentsummary_belge_tarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openorderdetail',
            name='sevk_adres',
            field=models.CharField(default=1, max_length=254, verbose_name='Sevk Adres'),
            preserve_default=False,
        ),
    ]
