# Generated by Django 4.2.7 on 2024-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0007_documentsummary_sevk_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openorderdetail',
            name='belge_durum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Durumu'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='belge_onay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Onay'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='kalem_grup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalem Grubu'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='musteri_ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='satici',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Satış Tipi'),
        ),
        migrations.AlterField(
            model_name='openorderdetail',
            name='sevk_adres',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sevk Adres'),
        ),
    ]
