# Generated by Django 4.2.7 on 2024-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openorderdocsum', '0008_alter_openorderdetail_belge_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_durum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Durumu'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_onay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Onayı'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='musteri_ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='satici',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Satış Tipi'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='sevk_adres',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sevk Adres'),
        ),
    ]
