# Generated by Django 4.2.7 on 2023-11-05 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HanaDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True, verbose_name='Tip Kodu')),
                ('type_description', models.CharField(max_length=255, verbose_name='Tip Açıklaması')),
                ('type_class', models.CharField(blank=True, choices=[('continuous_numeric', 'Sürekli Sayısal'), ('discrete_numeric', 'Ayrık Sayısal'), ('textual', 'Metinsel'), ('date_time', 'Tarih/Zaman'), ('boolean', 'Mantıksal'), ('spatial', 'Mekansal'), ('binary', 'İkilik'), ('large_object', 'Büyük Nesne'), ('array', 'Dizi'), ('enumeration', 'Sıralama'), ('alphanum', 'Alfanümerik')], default='other', max_length=20, null=True, verbose_name='Tip Sınıfı')),
                ('formatter_function_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Data - HANA Veri Tipi',
                'verbose_name_plural': 'Data - HANA Veri Tipleri',
            },
        ),
        migrations.CreateModel(
            name='NetworkPicturName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PictureName', models.CharField(max_length=255, unique=True, verbose_name='Resim Adı')),
            ],
            options={
                'verbose_name': 'Ağ - Resim Adı',
                'verbose_name_plural': 'Ağ - Resim Adları',
            },
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True, verbose_name='Tablo Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('query', models.TextField(verbose_name='SQL Sorgusu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('sys_table_columns', models.BooleanField(default=False, verbose_name='SYS.TABLE_COLUMNS Var mı?')),
            ],
            options={
                'verbose_name': 'Data - SQL Sorgusu',
                'verbose_name_plural': 'Data - SQL Sorguları',
            },
        ),
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True, verbose_name='Tablo Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('hana_data_set', models.JSONField(blank=True, default=dict, null=True, verbose_name='HANA DATA SET')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veri Çekme Tarihi')),
                ('sql_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicreport.sqlquery', verbose_name='SQL Sorgusu')),
            ],
            options={
                'verbose_name': 'Data - Dinamik Tablo',
                'verbose_name_plural': 'Data - Dinamik Tablolar',
            },
        ),
        migrations.CreateModel(
            name='DynamicHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, verbose_name='Tablo Adı')),
                ('line_no', models.IntegerField(verbose_name='Sıra Numarası')),
                ('header_name', models.CharField(max_length=255, verbose_name='Kolon Başlığı')),
                ('dynamic_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamicreport.dynamictable', verbose_name='Dinamik Tablo')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamicreport.hanadatatype', verbose_name='Kolon Tipi')),
            ],
            options={
                'verbose_name': 'Data - Dinamik Kolon Başlığı',
                'verbose_name_plural': 'Data - Dinamik Kolon Başlıkları',
            },
        ),
    ]
