# Generated by Django 4.2.7 on 2024-05-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicreport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkPicturName',
        ),
    ]
