# Generated by Django 4.2.7 on 2024-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belge_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Belge Numarası')),
                ('satici', models.CharField(blank=True, max_length=100, null=True, verbose_name='Satıcı')),
                ('belge_tarih', models.DateField(blank=True, null=True, verbose_name='Belge Tarihi')),
                ('teslim_tarih', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('belge_onay', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Onayı')),
                ('belge_durum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Durumu')),
                ('belge_aciklamasi', models.CharField(blank=True, max_length=254, null=True, verbose_name='Belge Aciklamasi')),
                ('sevk_adres', models.CharField(blank=True, max_length=254, null=True, verbose_name='Sevk Adres')),
                ('musteri_kod', models.CharField(db_index=True, max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_ad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri Adı')),
                ('satis_tipi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Satış Tipi')),
                ('net_tutar_ypb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Tutar YPB')),
                ('net_tutar_spb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Tutar SPB')),
            ],
            options={
                'verbose_name': 'Belge Özeti',
                'verbose_name_plural': 'Belge Özetleri',
            },
        ),
        migrations.CreateModel(
            name='SalesOfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniq_detail_no', models.CharField(max_length=100, unique=True, verbose_name='Benzersiz Detay Numarası')),
                ('belge_no', models.CharField(db_index=True, max_length=50, verbose_name='Belge Numarası')),
                ('satici', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Satıcı')),
                ('belge_tarih', models.DateField(blank=True, db_index=True, null=True, verbose_name='Belge Tarihi')),
                ('teslim_tarih', models.DateField(blank=True, db_index=True, null=True, verbose_name='Teslim Tarihi')),
                ('belge_onay', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Onay')),
                ('belge_durum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Durumu')),
                ('belge_aciklamasi', models.CharField(blank=True, max_length=254, null=True, verbose_name='Belge Aciklamasi')),
                ('sevk_adres', models.CharField(blank=True, max_length=254, null=True, verbose_name='Sevk Adres')),
                ('musteri_kod', models.CharField(db_index=True, max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_ad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri Adı')),
                ('satis_tipi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Satış Tipi')),
                ('kalem_grup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalem Grubu')),
                ('satir_durum', models.CharField(db_index=True, max_length=50, verbose_name='Satır Durumu')),
                ('satir_no', models.CharField(max_length=50, verbose_name='Satır Durumu')),
                ('kalem_kod', models.CharField(db_index=True, max_length=50, verbose_name='Kalem Kodu')),
                ('kalem_tanimi', models.CharField(db_index=True, max_length=200, verbose_name='Kalem Tanımı')),
                ('birim', models.CharField(max_length=50, verbose_name='Birim')),
                ('siparis_miktari', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sipariş Miktarı')),
                ('liste_fiyat_dpb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Liste Fiyatı DPB')),
                ('detay_kur', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Detay Kur')),
                ('detay_doviz', models.CharField(max_length=10, verbose_name='Detay Döviz')),
                ('iskonto_oran', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İskonto Oranı')),
                ('net_fiyat_dpb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Fiyat DPB')),
                ('net_tutar_ypb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Tutar YPB')),
                ('net_tutar_spb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Tutar SPB')),
            ],
            options={
                'verbose_name': 'Satis Teklif Detayı',
                'verbose_name_plural': 'Satis Teklif Detayları',
            },
        ),
    ]
