# Generated by Django 4.2.7 on 2024-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesofferdocsum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Net Tutar SPB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesofferdetail',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Tutar SPB'),
        ),
    ]
