# Generated by Django 4.2.7 on 2024-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesofferdocsum', '0002_documentsummary_brut_tutar_spb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_aciklamasi',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='BelgeAciklamasi'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_durum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BelgeDurumu'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_no',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='BelgeNo'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_onay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BelgeOnayı'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='BelgeTarihi'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BrutTutarSPB'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='musteri_ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MüşteriAdı'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='musteri_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='MüşteriKodu'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='net_tutar_spb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NetTutarSPB'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NetTutarYPB'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SatışTipi'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='sevk_adres',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='SevkAdres'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='teslim_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='TeslimTarihi'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='BrutTutarSPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='iskonto_oran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İskOranı'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='NetFiyatDPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='NetTutarSPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='NetTutarYPB'),
        ),
    ]
