# Generated by Django 4.2.7 on 2024-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesofferdocsum', '0003_alter_documentsummary_belge_aciklamasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofferdetail',
            name='belge_aciklamasi',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='BelgeAciklamasi'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='belge_durum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BelgeDurumu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='belge_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name='BelgeNumarası'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='belge_onay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BelgeOnay'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='belge_tarih',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='BelgeTarihi'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='detay_doviz',
            field=models.CharField(max_length=10, verbose_name='DetayDöviz'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='detay_kur',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='DetayKur'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='iskonto_oran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İskOran'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='kalem_grup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KalemGrubu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='kalem_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='KalemKodu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='kalem_tanimi',
            field=models.CharField(db_index=True, max_length=200, verbose_name='KalemTanımı'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='liste_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ListeFiyatıDPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='musteri_ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MüşteriAdı'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='musteri_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='MüşteriKodu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='satir_durum',
            field=models.CharField(db_index=True, max_length=50, verbose_name='SatırDurumu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='satir_no',
            field=models.CharField(max_length=50, verbose_name='SatırDurumu'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='satis_tipi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SatışTipi'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='sevk_adres',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='SevkAdres'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='siparis_miktari',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SiparişMiktarı'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='teslim_tarih',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='TeslimTarihi'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='uniq_detail_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='UniqDetayNumarası'),
        ),
    ]
