# Generated by Django 4.2.7 on 2024-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesofferdocsum', '0004_alter_salesofferdetail_belge_aciklamasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='elle_kapatilan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ElleKapatilan'),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='iptal_edilen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IptalEdilen'),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='siparise_aktarilan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SipariseAktarilan'),
        ),
        migrations.AddField(
            model_name='salesofferdetail',
            name='elle_kapatilan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ElleKapatilan'),
        ),
        migrations.AddField(
            model_name='salesofferdetail',
            name='iptal_edilen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IptalEdilen'),
        ),
        migrations.AddField(
            model_name='salesofferdetail',
            name='siparise_aktarilan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SipariseAktarilan'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='uniq_detail_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='UniqDetayNo'),
        ),
    ]
