# Generated by Django 4.2.7 on 2024-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesofferdocsum', '0005_documentsummary_elle_kapatilan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='BrutTutarSPB'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='net_tutar_spb',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='NetTutarSPB'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='NetTutarYPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='BrutTutarSPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='iskonto_oran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='İskOran'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='liste_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='ListeFiyatıDPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_fiyat_dpb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='NetFiyatDPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='NetTutarSPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='net_tutar_ypb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='NetTutarYPB'),
        ),
        migrations.AlterField(
            model_name='salesofferdetail',
            name='siparis_miktari',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='SiparişMiktarı'),
        ),
    ]
