# Generated by Django 5.2.5 on 2025-09-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSalesReportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Kaydın sistemde aktif olarak kullanılıp kullanılmayacağını belirtir.', verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kaydın veritabanına eklendiği tarih.', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kaydın son güncellendiği tarih.', verbose_name='Güncellenme Tarihi')),
                ('preset_name', models.CharField(help_text="Kullanıcının filtre setine verdiği isim (örn: 'Ahmet'in Aylık Bayi Raporu').", max_length=100, verbose_name='Filtre Seti Adı')),
                ('filters', models.JSONField(default=dict, help_text="Rapor için seçilen filtreleri JSON formatında tutar. Örn: {'satici': ['Ahmet Yılmaz'], 'cariGrup': ['BAYİ']}", verbose_name='Filtreler')),
                ('user', models.ForeignKey(help_text='Bu filtre setini oluşturan kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='sales_report_presets', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri Satış Raporu Filtre Seti',
                'verbose_name_plural': 'Müşteri Satış Raporu Filtre Setleri',
                'ordering': ['user', 'preset_name'],
                'unique_together': {('user', 'preset_name')},
            },
        ),
    ]
