# Generated by Django 5.0.8 on 2025-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSalesRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Kaydın sistemde aktif olarak kullanılıp kullanılmayacağını belirtir.', verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kaydın veritabanına eklendiği tarih.', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kaydın son güncellendiği tarih.', verbose_name='Güncellenme Tarihi')),
                ('satici', models.CharField(max_length=255, verbose_name='Satıcı')),
                ('satis_tipi', models.CharField(max_length=50, verbose_name='Satış Tipi')),
                ('cari_grup', models.CharField(max_length=100, verbose_name='Cari Grup')),
                ('musteri_kodu', models.CharField(max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_adi', models.CharField(max_length=255, verbose_name='Müşteri Adı')),
                ('toplam_net_spb_eur', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Toplam Net SPB EUR')),
                ('ocak', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ocak')),
                ('subat', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Şubat')),
                ('mart', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Mart')),
                ('nisan', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Nisan')),
                ('mayis', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Mayıs')),
                ('haziran', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Haziran')),
                ('temmuz', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Temmuz')),
                ('agustos', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ağustos')),
                ('eylul', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Eylül')),
                ('ekim', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ekim')),
                ('kasim', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Kasım')),
                ('aralik', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Aralık')),
            ],
            options={
                'verbose_name': 'Müşteri Satış Ham Verisi',
                'verbose_name_plural': 'Müşteri Satış Ham Verileri',
                'indexes': [models.Index(fields=['satici'], name='customersal_satici_6a63c8_idx'), models.Index(fields=['satis_tipi'], name='customersal_satis_t_1b8d78_idx'), models.Index(fields=['cari_grup'], name='customersal_cari_gr_33f796_idx')],
            },
        ),
    ]
