# Generated by Django 5.2.5 on 2025-09-02 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersalesreportpreset',
            name='filters',
            field=models.JSONField(default=dict, verbose_name='Filtreler'),
        ),
        migrations.AlterField(
            model_name='customersalesreportpreset',
            name='preset_name',
            field=models.CharField(max_length=100, verbose_name='Filtre Seti Adı'),
        ),
        migrations.AlterField(
            model_name='customersalesreportpreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_report_presets', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='CustomerSalesRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satici', models.CharField(max_length=255, verbose_name='Satıcı')),
                ('satis_tipi', models.CharField(max_length=50, verbose_name='Satış Tipi')),
                ('cari_grup', models.CharField(max_length=100, verbose_name='Cari Grup')),
                ('musteri_kodu', models.CharField(max_length=50, verbose_name='Müşteri Kodu')),
                ('musteri_adi', models.CharField(max_length=255, verbose_name='Müşteri Adı')),
                ('toplam_net_spb_eur', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Toplam Net SPB EUR')),
                ('ocak', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ocak')),
                ('subat', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Şubat')),
                ('mart', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Mart')),
                ('nisan', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Nisan')),
                ('mayis', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Mayıs')),
                ('haziran', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Haziran')),
                ('temmuz', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Temmuz')),
                ('agustos', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ağustos')),
                ('eylul', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Eylül')),
                ('ekim', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Ekim')),
                ('kasim', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Kasım')),
                ('aralik', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Aralık')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Müşteri Satış Ham Verisi',
                'verbose_name_plural': 'Müşteri Satış Ham Verileri',
                'indexes': [models.Index(fields=['satici'], name='customersal_satici_6a63c8_idx'), models.Index(fields=['satis_tipi'], name='customersal_satis_t_1b8d78_idx'), models.Index(fields=['cari_grup'], name='customersal_cari_gr_33f796_idx')],
            },
        ),
    ]
