# Generated by Django 5.2.5 on 2025-09-02 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersales', '0002_alter_customersalesreportpreset_filters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersalesrawdata',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='customersalesrawdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 2, 14, 23, 40, 875141, tzinfo=datetime.timezone.utc), help_text='Kaydın veritabanına eklendiği tarih.', verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersalesrawdata',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Kaydın sistemde aktif olarak kullanılıp kullanılmayacağını belirtir.', verbose_name='Aktif Mi?'),
        ),
        migrations.AddField(
            model_name='customersalesrawdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Kaydın son güncellendiği tarih.', verbose_name='Güncellenme Tarihi'),
        ),
        migrations.DeleteModel(
            name='CustomerSalesReportPreset',
        ),
    ]
