# Generated by Django 4.2.7 on 2024-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(max_length=20, unique=True)),
                ('cari_adi', models.CharField(max_length=255)),
                ('temsilci', models.CharField(blank=True, max_length=255, null=True)),
                ('cari_grup', models.CharField(blank=True, max_length=255, null=True)),
                ('gunluk_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('son_on_gun_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('aylik_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('yillik_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('acik_sevkiyat_toplami', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('acik_siparis_toplami', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('irsaliye_sayisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Delivery Document Summary',
                'verbose_name_plural': 'Delivery Document Summaries',
            },
        ),
    ]
