# Generated by Django 4.2.7 on 2024-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverydocsum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydocsummary',
            name='cari_adi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
