# Generated by Django 4.2.7 on 2024-04-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverydocsum', '0002_alter_deliverydocsummary_cari_adi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydocsummary',
            old_name='son_on_gun_toplam',
            new_name='dun_toplam',
        ),
        migrations.AddField(
            model_name='deliverydocsummary',
            name='dun_ilgili_siparis_numaralari',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='deliverydocsummary',
            name='evdun_toplam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='deliverydocsummary',
            name='gunluk_ilgili_siparis_numaralari',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='deliverydocsummary',
            name='onceki_gun_ilgili_siparis_numaralari',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
