# Generated by Django 4.2.7 on 2024-04-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverydocsum', '0003_rename_son_on_gun_toplam_deliverydocsummary_dun_toplam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydocsummary',
            old_name='evdun_toplam',
            new_name='onceki_gun_toplam',
        ),
    ]
