# Generated by Django 5.0.8 on 2024-10-06 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('last_scanned', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesharehub.directory')),
            ],
            options={
                'permissions': [('read_file', 'Can read file'), ('download_file', 'Can download file')],
                'unique_together': {('directory', 'filename')},
            },
        ),
    ]
