# Generated by Django 5.0.8 on 2025-03-07 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productconfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('name', models.CharField(max_length=255, verbose_name='Simülasyon Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('level', models.CharField(choices=[('brand', 'Marka Seviyesi'), ('product_group', 'Ürün Grubu Seviyesi'), ('category', 'Kategori Seviyesi'), ('product_model', 'Ürün Modeli Seviyesi')], default='product_model', max_length=20, verbose_name='Simülasyon Seviyesi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('max_variants_per_model', models.PositiveIntegerField(default=1000, help_text='Bir model için oluşturulacak maksimum varyant sayısı', verbose_name='Model Başına Maksimum Varyant')),
                ('include_dependent_rules', models.BooleanField(default=True, help_text='Bağımlı kuralları simülasyona dahil et', verbose_name='Bağımlı Kuralları Dahil Et')),
                ('include_conditional_options', models.BooleanField(default=True, help_text='Koşullu seçenekleri simülasyona dahil et', verbose_name='Koşullu Seçenekleri Dahil Et')),
                ('include_price_multipliers', models.BooleanField(default=True, help_text='Fiyat çarpanlarını simülasyona dahil et', verbose_name='Fiyat Çarpanlarını Dahil Et')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('total_models', models.PositiveIntegerField(default=0, verbose_name='Toplam Model Sayısı')),
                ('processed_models', models.PositiveIntegerField(default=0, verbose_name='İşlenen Model Sayısı')),
                ('total_variants', models.PositiveIntegerField(default=0, verbose_name='Toplam Varyant Sayısı')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Toplam Hata Sayısı')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='Sonuç Özeti')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='productconfig.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='productconfig.category', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='productconfig.productgroup', verbose_name='Ürün Grubu')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='productconfig.productmodel', verbose_name='Ürün Modeli')),
            ],
            options={
                'verbose_name': 'Simülasyon İşi',
                'verbose_name_plural': 'Simülasyon İşleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('error_type', models.CharField(choices=[('missing_options', 'Seçeneği Eksik Soru'), ('dependent_rule_error', 'Bağımlı Kural Hatası'), ('conditional_option_error', 'Koşullu Seçenek Hatası'), ('price_multiplier_error', 'Fiyat Çarpan Hatası'), ('processing_error', 'İşlem Hatası'), ('data_inconsistency', 'Veri Tutarsızlığı')], max_length=30, verbose_name='Hata Tipi')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('error', 'Hata'), ('critical', 'Kritik')], default='error', max_length=10, verbose_name='Önem Derecesi')),
                ('message', models.TextField(verbose_name='Hata Mesajı')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detaylar')),
                ('resolution_status', models.BooleanField(default=False, verbose_name='Çözüldü mü?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Zamanı')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Çözüm Notları')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_errors', to='productconfig.option', verbose_name='Seçenek')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_errors', to='productconfig.productmodel', verbose_name='Ürün Modeli')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_errors', to='productconfig.question', verbose_name='Soru')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_simulation_errors', to=settings.AUTH_USER_MODEL, verbose_name='Çözen Kullanıcı')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='productconfig_simulator.simulationjob', verbose_name='Simülasyon')),
            ],
            options={
                'verbose_name': 'Simülasyon Hatası',
                'verbose_name_plural': 'Simülasyon Hataları',
                'ordering': ['-created_at', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('variant_code', models.CharField(max_length=255, verbose_name='Varyant Kodu')),
                ('variant_description', models.TextField(blank=True, verbose_name='Varyant Tanımı')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Fiyat')),
                ('text_answers', models.JSONField(blank=True, default=dict, verbose_name='Metin Cevaplar')),
                ('old_component_codes', models.JSONField(blank=True, default=list, verbose_name='Eski Bileşen Kodları')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_variants', to='productconfig.productmodel', verbose_name='Ürün Modeli')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='simulated_variants', to='productconfig.option', verbose_name='Seçilen Seçenekler')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='productconfig_simulator.simulationjob', verbose_name='Simülasyon')),
            ],
            options={
                'verbose_name': 'Simüle Edilmiş Varyant',
                'verbose_name_plural': 'Simüle Edilmiş Varyantlar',
                'ordering': ['product_model', 'variant_code'],
            },
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['status'], name='productconf_status_b87223_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['level'], name='productconf_level_b43554_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['brand'], name='productconf_brand_i_2bd156_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['product_group'], name='productconf_product_25b747_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['category'], name='productconf_categor_fe6423_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationjob',
            index=models.Index(fields=['product_model'], name='productconf_product_5e13f7_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationerror',
            index=models.Index(fields=['simulation', 'error_type'], name='productconf_simulat_5f289d_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationerror',
            index=models.Index(fields=['resolution_status'], name='productconf_resolut_b29a41_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationerror',
            index=models.Index(fields=['product_model'], name='productconf_product_653af8_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedvariant',
            index=models.Index(fields=['simulation', 'product_model'], name='productconf_simulat_29052a_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedvariant',
            index=models.Index(fields=['variant_code'], name='productconf_variant_64618a_idx'),
        ),
    ]
