# Generated by Django 5.0.8 on 2025-03-01 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HANADBIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_name', models.CharField(help_text='Entegrasyon adı', max_length=255, unique=True)),
                ('integration_type', models.CharField(choices=[('stock_card', 'Stok Kart Entegrasyonu'), ('sales_order', 'Satış Siparişi Entegrasyonu'), ('inventory', 'Stok Yönetimi Entegrasyonu')], help_text='Entegrasyon tipi', max_length=50)),
                ('external_api_url', models.URLField(help_text='Bağımsız entegrasyon API adresi')),
                ('hana_status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', help_text='HANA DB ile senkronizasyon durumu', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Son senkronizasyon tarihi', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
