# Generated by Django 5.0.8 on 2025-06-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunainstotalrisk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalRiskReport',
            new_name='TunainsTotalRiskReport',
        ),
        migrations.AlterModelOptions(
            name='tunainstotalriskreport',
            options={'verbose_name': 'Tunains Toplam Risk Raporu', 'verbose_name_plural': 'Tunains Toplam Risk Raporları'},
        ),
        migrations.AlterModelTable(
            name='tunainstotalriskreport',
            table='tunainstotalrisk_report',
        ),
    ]
