# Generated by Django 5.0.8 on 2025-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunainstotalrisk', '0002_rename_totalriskreport_tunainstotalriskreport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tunainstotalriskreport',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Tunains Toplam Risk Raporu', 'verbose_name_plural': 'Tunains Toplam Risk Raporları'},
        ),
        migrations.AddField(
            model_name='tunainstotalriskreport',
            name='source',
            field=models.CharField(default='tunains', editable=False, help_text='Kaydın hangi micro‑servisten geldiğini belirtir', max_length=32),
        ),
        migrations.AlterField(
            model_name='tunainstotalriskreport',
            name='muhatap_kod',
            field=models.CharField(max_length=50, verbose_name='Muhatap Kod'),
        ),
        migrations.AddConstraint(
            model_name='tunainstotalriskreport',
            constraint=models.UniqueConstraint(fields=('muhatap_kod',), name='uniq_tunains_muhatap'),
        ),
    ]
