# Generated by Django 4.2.7 on 2024-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kodu', models.CharField(db_index=True, max_length=50)),
                ('cari_aciklamasi', models.CharField(max_length=255)),
                ('bakiye', models.FloatField()),
            ],
            options={
                'verbose_name': 'Customer Balance',
                'verbose_name_plural': 'Customer Balances',
                'db_table': 'customer_balance',
                'indexes': [models.Index(fields=['cari_kodu'], name='customer_ba_cari_ko_d85de2_idx')],
            },
        ),
    ]
