# Generated by Django 4.2.7 on 2024-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logocustomerbalance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbalance',
            old_name='bakiye',
            new_name='bakiye_alacak',
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='bakiye_borc',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
