# Generated by Django 4.2.7 on 2024-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satici', models.CharField(max_length=100)),
                ('yil', models.IntegerField()),
                ('toplam_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toplam_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oca_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oca_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('may_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haz_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haz_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tem_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tem_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agu_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agu_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eyl_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eyl_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eki_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eki_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kas_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kas_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ara_gercek', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ara_hedef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
