# Generated by Django 4.2.7 on 2024-03-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesbudget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbudget',
            name='yil',
        ),
    ]
