# Generated by Django 5.0.8 on 2025-05-17 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(help_text="Bu rapora özel kısa sistem adı (örn. 'balance_top10')", max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('passive', 'Pasif (ham veriyi al + filtrele)'), ('active', 'Aktif (veriyi tetikle + bekle + özet veriyi al)')], default='passive', help_text='Rapor modu: pasif veya aktif tetikleyicili yapı', max_length=10)),
                ('trigger_url', models.URLField(blank=True, help_text='Aktif modda veriyi tetiklemek için kullanılacak endpoint', null=True)),
                ('data_pull_url', models.URLField(help_text='Veriyi çekeceğimiz canlı endpoint (aktif modda özet veriyi verir)')),
                ('wait_seconds', models.IntegerField(default=300, help_text='Tetikleme sonrası bekleme süresi (aktif mod için saniye cinsinden)')),
                ('rule_json', models.JSONField(default=dict, help_text='Veri üzerinde sıralama, filtreleme, limit ve doğrulama kuralları')),
                ('result_json', models.JSONField(blank=True, default=dict, help_text='İşlenmiş, doğrulanmış ve sisteme kaydedilmiş özet veri', null=True)),
                ('last_error_message', models.TextField(blank=True, help_text='Son hata mesajı (varsa)', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Son başarılı çalıştırma zamanı', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Bu rapor aktif mi? (pasif yapılırsa sabah çalışmaz)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Rapor Modeli',
                'verbose_name_plural': 'API Rapor Modelleri',
            },
        ),
        migrations.CreateModel(
            name='APIExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Başarılı'), ('FAILED', 'Hatalı')], default='SUCCESS', help_text='Raporun çalıştırma sonucu', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Hata oluştuysa hata mesajı', null=True)),
                ('run_date', models.DateField(default=django.utils.timezone.now, help_text='Raporun çalıştığı tarih (günlük özet için)')),
                ('run_time', models.DateTimeField(auto_now_add=True, help_text='Çalıştırma anı (tam timestamp)')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='İşlem süresi (isteğe bağlı performans ölçümü için)', null=True)),
                ('api', models.ForeignKey(help_text='Çalıştırılan raporun referansı', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='report_orchestrator.apireportmodel')),
            ],
            options={
                'verbose_name': 'API Rapor Çalışma Kaydı',
                'verbose_name_plural': 'API Rapor Çalışma Kayıtları',
                'ordering': ['-run_time'],
            },
        ),
    ]
