# Generated by Django 4.2.7 on 2024-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cari_kod', models.CharField(max_length=100)),
                ('cari_ad', models.CharField(max_length=255)),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=19)),
                ('öncesi', models.DecimalField(decimal_places=2, max_digits=19)),
                ('monthly_balances', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firma_kod', models.CharField(max_length=100)),
                ('kaynak_pro', models.CharField(max_length=100)),
                ('cari_kod', models.CharField(max_length=100)),
                ('cari_ad', models.CharField(max_length=255)),
                ('belge_tarih', models.DateField()),
                ('belge_no', models.IntegerField()),
                ('vade_tarih', models.DateField()),
                ('iban', models.CharField(max_length=34)),
                ('odemekod', models.IntegerField()),
                ('odemekosulu', models.CharField(max_length=255)),
                ('borc', models.DecimalField(decimal_places=2, max_digits=19)),
                ('alacak', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'ordering': ['belge_tarih'],
            },
        ),
    ]
