# Generated by Django 4.2.7 on 2024-03-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='belge_tarih',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='vade_tarih',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
