# Generated by Django 4.2.7 on 2024-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0002_alter_supplierpayment_belge_tarih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
