# Generated by Django 4.2.7 on 2024-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0003_alter_supplierpayment_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='cari_kod',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
