# Generated by Django 4.2.7 on 2024-03-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0004_alter_closinginvoice_cari_kod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closinginvoice',
            old_name='toplam',
            new_name='bakiye',
        ),
    ]
