# Generated by Django 4.2.7 on 2024-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0005_rename_toplam_closinginvoice_bakiye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='öncesi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
