# Generated by Django 4.2.7 on 2024-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0006_alter_closinginvoice_öncesi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closinginvoice',
            old_name='bakiye',
            new_name='current_balance',
        ),
        migrations.RemoveField(
            model_name='closinginvoice',
            name='öncesi',
        ),
        migrations.AddField(
            model_name='closinginvoice',
            name='previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
