# Generated by Django 4.2.7 on 2024-03-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0007_rename_bakiye_closinginvoice_current_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closinginvoice',
            name='previous',
        ),
    ]
