# Generated by Django 4.2.7 on 2024-03-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0008_remove_closinginvoice_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closinginvoice',
            name='cari_ad',
        ),
    ]
