# Generated by Django 4.2.7 on 2024-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0009_remove_closinginvoice_cari_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='closinginvoice',
            name='cari_ad',
            field=models.CharField(default=8, max_length=255),
            preserve_default=False,
        ),
    ]
