# Generated by Django 4.2.7 on 2024-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0010_closinginvoice_cari_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='monthly_balances',
            field=models.JSONField(null=True),
        ),
    ]
