# Generated by Django 4.2.7 on 2024-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0011_alter_closinginvoice_monthly_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='closinginvoice',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='closinginvoice',
            name='odemekosulu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='cari_ad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
