# Generated by Django 4.2.7 on 2024-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0012_closinginvoice_iban_closinginvoice_odemekosulu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='firma_kod',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='kaynak_pro',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='odemekod',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='vade_tarih',
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='cari_ad',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='cari_kod',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='current_balance',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='belge_no',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='belge_tarih',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='cari_ad',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='cari_kod',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
