# Generated by Django 5.0.8 on 2024-10-02 20:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0013_remove_supplierpayment_firma_kod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='cari_ad',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='current_balance',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='iban',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='closinginvoice',
            name='odemekosulu',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='alacak',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='borc',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='cari_ad',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='odemekosulu',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='closinginvoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['monthly_balances'], name='monthly_balances_gin'),
        ),
        migrations.AddIndex(
            model_name='closinginvoice',
            index=models.Index(fields=['current_balance', 'cari_kod'], name='curr_bal_cari_kod_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['cari_kod', 'belge_tarih'], name='supplierpay_cari_ko_121c59_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['cari_kod', 'belge_no'], name='supplierpay_cari_ko_a7934f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['borc', 'alacak'], name='supplierpay_borc_bf7d55_idx'),
        ),
    ]
