# Generated by Django 5.0.8 on 2024-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0014_alter_closinginvoice_cari_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='iban',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='iban',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
