# Generated by Django 5.0.8 on 2024-11-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0015_alter_closinginvoice_iban_alter_supplierpayment_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closinginvoice',
            name='iban',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='iban',
            field=models.TextField(blank=True, null=True),
        ),
    ]
