# Generated by Django 5.0.8 on 2025-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpayment', '0016_alter_closinginvoice_iban_alter_supplierpayment_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='is_buffer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['is_buffer', 'belge_tarih'], name='supplierpay_is_buff_7c3322_idx'),
        ),
    ]
