# Generated by Django 5.0.8 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemnotebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnote',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
