# Generated by Django 5.0.8 on 2025-06-17 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemnotebook', '0002_alter_systemnote_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='systemnote',
            constraint=models.UniqueConstraint(fields=('title', 'source', 'created_at'), name='unique_note_per_minute'),
        ),
    ]
