# Generated by Django 5.0.8 on 2025-06-17 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemnotebook', '0003_systemnote_unique_note_per_minute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='systemnote',
            name='unique_note_per_minute',
        ),
        migrations.AddConstraint(
            model_name='systemnote',
            constraint=models.UniqueConstraint(fields=('created_at',), name='unique_created_at_note'),
        ),
    ]
