# Generated by Django 5.0.8 on 2025-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemnotebook', '0004_remove_systemnote_unique_note_per_minute_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='systemnote',
            name='unique_created_at_note',
        ),
        migrations.AddField(
            model_name='systemnote',
            name='commit_sha',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True, verbose_name='Git commit SHA'),
        ),
        migrations.AlterField(
            model_name='systemnote',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
