# Generated by Django 5.0.8 on 2025-03-01 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('main_item', models.CharField(max_length=50, verbose_name='Ana Ürün Kodu')),
                ('sub_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Ürün/Kod')),
                ('component_item_code', models.CharField(max_length=50, verbose_name='Bileşen Stok Kodu')),
                ('component_item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bileşen Adı')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Miktar')),
                ('level', models.IntegerField(verbose_name='BOM Seviyesi')),
                ('type_description', models.CharField(max_length=50, verbose_name='Kalem Tipi')),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Son Satın Alma Fiyatı')),
                ('currency', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('rate', models.DecimalField(decimal_places=4, default=1, max_digits=18, verbose_name='Döviz Kuru')),
                ('last_purchase_price_upb', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Birim Satın Alma Fiyatı')),
                ('price_source', models.CharField(default='Taban Fiyat', max_length=50, verbose_name='Fiyat Kaynağı')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Belge Tarihi')),
                ('component_cost_upb', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Bileşen Maliyeti')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Satış Fiyatı')),
                ('sales_currency', models.CharField(default='TRY', max_length=10, verbose_name='Satış Para Birimi')),
                ('price_list_name', models.CharField(default='YOK', max_length=50, verbose_name='Fiyat Listesi Adı')),
                ('item_group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün Grubu')),
                ('new_last_purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='Kullanıcı tarafından girilebilen yeni son satın alma fiyatı (override)', max_digits=18, verbose_name='Yeni Son Satın Alma Fiyatı')),
                ('new_currency', models.CharField(default='', help_text='Kullanıcı tarafından girilebilen yeni döviz cinsi (override). Boş bırakılırsa orijinal değer kullanılır.', max_length=10, verbose_name='Yeni Döviz')),
                ('labor_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Ham madde maliyeti üzerine uygulanacak işçilik çarpanı', max_digits=10, verbose_name='İşçilik Çarpanı')),
                ('overhead_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Ham madde maliyeti üzerine uygulanacak genel üretim gideri çarpanı', max_digits=10, verbose_name='Genel Üretim Gideri Çarpanı')),
                ('license_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Ürün üzerindeki lisans ve komisyon giderlerini hesaplamak için kullanılacak çarpan', max_digits=10, verbose_name='Lisans Çarpanı')),
                ('commission_multiplier', models.DecimalField(decimal_places=4, default=1, help_text='Ürün satışından doğan komisyon giderlerini hesaplamak için kullanılacak çarpan', max_digits=10, verbose_name='Komisyon Çarpanı')),
                ('updated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Ham madde maliyeti, override fiyatı ve master çarpanların (işçilik, genel gider, lisans, komisyon) ile hesaplanmış nihai maliyet', max_digits=18, verbose_name='Güncel Maliyet')),
            ],
            options={
                'verbose_name': 'BOM Kalemi',
                'verbose_name_plural': 'BOM Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='BOMProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('item_code', models.CharField(max_length=50, verbose_name='Ürün Kodu')),
                ('item_name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('default_wh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Varsayılan Depo')),
                ('invnt_item', models.BooleanField(default=True, verbose_name='Stok Kalemi')),
                ('sell_item', models.BooleanField(default=True, verbose_name='Satılabilir')),
                ('purch_item', models.BooleanField(default=True, verbose_name='Satın Alınabilir')),
                ('sales_price_list', models.CharField(default='YOK', max_length=50, verbose_name='Satış Fiyat Listesi')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Satış Fiyatı')),
                ('currency', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('bom_create_date', models.DateField(blank=True, null=True, verbose_name='BOM Oluşturma Tarihi')),
                ('bom_update_date', models.DateField(blank=True, null=True, verbose_name='BOM Güncelleme Tarihi')),
                ('created_user_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oluşturan Kullanıcı Kodu')),
                ('updated_user_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Güncelleyen Kullanıcı Kodu')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BOM Ürünü',
                'verbose_name_plural': 'BOM Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='BOMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('project_name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'BOM Kaydı',
                'verbose_name_plural': 'BOM Kayıtları',
            },
        ),
    ]
