# Generated by Django 4.2.7 on 2024-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0002_documentsummary_net_tutar_spb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_aciklamasi',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Belge Aciklamasi'),
        ),
    ]
