# Generated by Django 4.2.7 on 2024-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0003_alter_documentsummary_belge_aciklamasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsummary',
            name='girsberger_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='documentsummary',
            name='mamul_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='documentsummary',
            name='montaj_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='documentsummary',
            name='nakliye_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='documentsummary',
            name='ticari_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='girsberger_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='mamul_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='montaj_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='nakliye_net_tutar_ypb',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='ticari_net_tutar_ypb',
        ),
    ]
