# Generated by Django 4.2.7 on 2024-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0004_remove_documentsummary_girsberger_net_tutar_ypb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsummary',
            name='belge_no',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Belge Numarası'),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='musteri_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Müşteri Kodu'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Belge Numarası'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='belge_tarih',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Belge Tarihi'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='musteri_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Müşteri Kodu'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satici',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='satir_durum',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Satır Durumu'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='teslim_tarih',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Teslim Tarihi'),
        ),
    ]
