# Generated by Django 4.2.7 on 2024-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0005_alter_documentsummary_belge_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdetail',
            name='satir_no',
            field=models.CharField(default=1, max_length=50, verbose_name='Satır Durumu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalem_kod',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Kalem Kodu'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='kalem_tanimi',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Kalem Tanımı'),
        ),
    ]
