# Generated by Django 5.0.8 on 2024-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0006_salesorderdetail_satir_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdetail',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='BrutTutarSPB'),
        ),
    ]
