# Generated by Django 5.0.8 on 2024-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorderdocsum', '0007_salesorderdetail_brut_tutar_spb'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='brut_tutar_spb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Brut Tutar SPB'),
        ),
    ]
