# Generated by Django 5.0.8 on 2024-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yil', models.IntegerField()),
                ('yil_ay', models.CharField(max_length=7)),
                ('teslimat_tutar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('teslimat_girsberger', models.DecimalField(decimal_places=2, max_digits=20)),
                ('teslimat_mamul', models.DecimalField(decimal_places=2, max_digits=20)),
                ('teslimat_ticari', models.DecimalField(decimal_places=2, max_digits=20)),
                ('teslimat_nakliye', models.DecimalField(decimal_places=2, max_digits=20)),
                ('teslimat_montaj', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Teslimat Özeti',
                'verbose_name_plural': 'Teslimat Özetleri',
                'ordering': ['-yil', '-yil_ay'],
                'unique_together': {('yil', 'yil_ay')},
            },
        ),
    ]
