# Generated by Django 5.0.8 on 2024-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroupdeliverysum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverysummary',
            options={'verbose_name': 'Teslimat Özeti', 'verbose_name_plural': 'Teslimat Özetleri'},
        ),
        migrations.AlterField(
            model_name='deliverysummary',
            name='yil',
            field=models.CharField(max_length=4),
        ),
    ]
