# Generated by Django 4.2.7 on 2024-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcentral', '0001_initial'),
        ('hanadbcon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlquery',
            old_name='position',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='queries_departments', to='authcentral.department'),
        ),
    ]
