# Generated by Django 5.0.8 on 2024-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanadbcon', '0002_rename_position_sqlquery_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='guidance_text',
            field=models.TextField(blank=True, default='\n        Parametrik SQL Sorgusu Oluşturma Klavuzu:\n        - Sorgunuzda parametre kullanmak için, parametre yerine \'?\' sembolünü kullanın.\n        - Şema bilgisini sorgunuzda "{schema}" placeholder\'ı ile belirtin.\n\n        Örnek Parametre: [{"name": "variant_code", "type": "string", "description": "Varyant Kodu"}]\n        \n        Örnek Sorgu:\n        SELECT\n            I."ItemCode",\n            COALESCE(I."ItemName", \'YOK\') AS "ItemName",\n            COALESCE(ITM1."Price", 0) AS "Price",\n            COALESCE(ITM1."Currency", \'YOK\') AS "Currency"\n        FROM\n            {schema}."OITM" I\n        LEFT JOIN\n            {schema}."ITM1" ITM1 ON I."ItemCode" = ITM1."ItemCode" AND ITM1."PriceList" = 1\n        WHERE\n            I."ItemCode" = ?;\n\n        - Bu sorguda \'variant_code\' parametresi kullanılmaktadır.\n        - API çağrısında URL şu şekilde olmalıdır:\n        /api/v2/hanadbcon/query/query_variant_status_hana_db/?variant_code=30.BW.A14090.M1.E1&schema=TUNADB24\n\n        - Parametreler query string\'de sağlanır ve SQL sorgusunda güvenli olarak bağlanır.\n        '),
        ),
    ]
