# Generated by Django 5.0.8 on 2025-07-01 13:36

import django.contrib.postgres.indexes
import logocustomercollection.models.base
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCustomerCollectionAgingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('cari_kod', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cari Kod')),
                ('cari_ad', models.CharField(db_index=True, max_length=255, verbose_name='Cari Ad')),
                ('guncel_bakiye', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Güncel Bakiye')),
                ('aylik_kalan_borc', models.JSONField(null=True, verbose_name='Aylık Kalan Borçlar')),
            ],
            options={
                'verbose_name': 'Müşteri Özet Yaşlandırma',
                'verbose_name_plural': 'Müşteri Özet Yaşlandırmalar',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['aylik_kalan_borc'], name='lcc_aylik_kalan_borc_gin'), models.Index(fields=['guncel_bakiye', 'cari_kod'], name='lcc_guncel_bakiye_cari_kod_idx')],
            },
            bases=(logocustomercollection.models.base.DecimalFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LogoCustomerCollectionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_kod', models.CharField(max_length=64, verbose_name='Cari Kod')),
                ('cari_ad', models.CharField(max_length=255, verbose_name='Cari Ad')),
                ('ay', models.PositiveSmallIntegerField(verbose_name='Ay')),
                ('yil', models.PositiveIntegerField(verbose_name='Yıl')),
                ('borc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Borç')),
                ('alacak', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Alacak')),
            ],
            options={
                'verbose_name': 'Logo Müşteri Ham İşlem',
                'verbose_name_plural': 'Logo Müşteri Ham İşlemler',
                'db_table': 'logocustomercollection_transaction_view',
                'indexes': [models.Index(fields=['cari_kod', 'yil', 'ay'], name='lcc_cari_kod_yil_ay_idx')],
                'unique_together': {('cari_kod', 'ay', 'yil')},
            },
        ),
    ]
