# Generated by Django 5.0.8 on 2025-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesbudgetv2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesBudget',
            new_name='SalesBudgetv2',
        ),
    ]
